### PR TITLE
Update iOS DeviceInfo.Model to return specific hw.machine 

### PR DESCRIPTION
**Pull request by jamesmontemagno**
via:
https://github.com/xamarin/xamarin-macios/blob/bc492585d137d8c3d3a2ffc827db3cdaae3cc869/tests/linker/ios/link%20sdk/LinkSdkRegressionTest.cs#L603-L631

Added tests

### Description of Change ###

Describe your changes here. 

### Bugs Fixed ###

- Related to issue #366

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

None

### Behavioral Changes ###

Instead of just returning iPhone/iPad will return model number such as iPad6,3

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs](https://github.com/xamarin/Essentials/blob/feature/issue-366/DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs](https://github.com/xamarin/Essentials/blob/feature/issue-366/Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Platform/Platform.ios.cs](https://github.com/xamarin/Essentials/blob/feature/issue-366/Xamarin.Essentials/Platform/Platform.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807192154582475-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rJ9UTzoWMMzRfS77i0QBhUJMfepYVou9HDQMLuF8YwU%3D&st=2018-07-19T21%3A50%3A53Z&se=2018-08-19T21%3A55%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs](https://github.com/xamarin/Essentials/blob/feature/issue-366/DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs](https://github.com/xamarin/Essentials/blob/feature/issue-366/Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Platform/Platform.ios.cs](https://github.com/xamarin/Essentials/blob/feature/issue-366/Xamarin.Essentials/Platform/Platform.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807192157285632-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=e63Xxrd%2FVR0fu6wn5k8Z0Pe2dPEpEUzRDk4M1xfdjOM%3D&st=2018-07-19T21%3A53%3A25Z&se=2018-08-19T21%3A58%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by stefandevo** [comment]
@jamesmontemagno thanks for this.
Please have a look at a maintained list of hardware identifiers:
https://github.com/fieldnotescommunities/ios-device-identifiers
This way you can map `iPhone10,6` to `iPhone X`

**Comment by Redth** [comment]
@stefandevo I'm a little concerned that if we add this kind of mapping, it becomes a bit of a pain to maintain and is more likely to be forgotten.  I'm leaning towards developers should just detect the actual hardware id, and not provide any sort of mapping.  I'm only a bit torn because it certainly is more convenient to have the mapping.

@jamesmontemagno thoughts?

**Comment by stefandevo** [comment]
Understand the concern, but EVERYONE will start using an extra nuget package for this mapping, because the hardware_id itself will nobody use; for Android you get a clean model name, so would expect the same for Apple devices; and of course you have to maintain it, but hey, it's opensource here so you have followers enough to just add these couple of mappings per year (if they bring new devices). :-)

**Comment by Redth** [comment]
@stefandevo for now we are going to leave this out.  I appreciate the concern around this, but one of the guiding principles we follow with this lib is to start out simple and not overcomplicate the API before we see enough demand.

There's also the issue of providing BOTH id's, and how that translates across platforms, or do we make a platform specific API for it, etc. 

I'm sure some users will be bothered by not having the mappings, but it's pretty trivial in reality to figure out which ID you need for example for the iPhone X.  We'll start without this, and if there's enough demand for it, revisit the issue at that point.

**Comment by stefandevo** [comment]
If you ever want to include the "PrettyModel" you are invited to use:
https://github.com/CaveBirdLabs/CaveBirdLabs.Xamarin.Essentials/blob/master/src/DeviceInfo.ios.extension.cs
I will keep this up to date; other devs can use the package if they want to Pretty-fy the model name

**Pull request merged**
