### PR TITLE
Documentation change - tiny typo

### PR DESCRIPTION
**Pull request by TrueGeek**
### Description of Change ###

Changed 'android' to 'Android'

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Can you base off of develop branch and not live :) sorry about that.

**Comment by TrueGeek** [comment]
Tried the develop branch but it's not happy their either. Sorry - did know a typo PR would cause trouble. :)

**Comment by mattleibow** [comment]
@TrueGeek I think I fixed it. I tried to merge but I think I broke things. So I rebased. Just check to see I got all your changes.

**Comment by TrueGeek** [comment]
> @mattleibow Just check to see I got all your changes.

Not sure if it publishes immediately but it's not showing as changed here yet:

https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.appinfo.packagename?view=xamarin-essentials

**Pull request merged**
