### PR TITLE
Fix #1972 - allow restricted permissions for geolocation on android

### LINKED ISSUE #1972: [Bug] Approximate location on Android 12 doesn't work correct.
### Description
      Can not get approximate location on android 12 because:
      line (Permissions.EnsureGrantedAsync<Permissions.LocationWhenInUse>())  expected only permissions granted:
  https://github.com/xamarin/Essentials/blob/72dda322aaa583873eb517b44fdcba3e87e5f35f/Xamarin.Essentials/Geolocation/Geolocation.android.cs#L40

### Steps to Reproduce

1. Select approximate location in popup
2. Try to get permissions for locationInUse => Restricted 
3. Try to get location => inner exception

### Expected Behavior
     Geolocation gets approximate location on android 12
### Actual Behavior
    Geolocation throw exception
 ### Basic Information

- Version with issue:
- Platform Target Frameworks: 
  - Android:

### PR DESCRIPTION
**Pull request by aritchie**
### Description of Change ###
Allow restricted permissions for "gatekeepers" on android geolocation methods

### Bugs Fixed ###

- Related to issue #
(https://github.com/xamarin/Essentials/issues/1972)

### API Changes ###

Optional parameter added to Permissions.EnsureGrantedAsync that also allows restricted to pass internal gatekeepers.  Default is set to false, so only methods where this is required functionality will care

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [X] Rebased on top of `main` at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Should we add  a new method instead called "EnsureGrantedOrRrestrictedAsync". I am not a super fan of more overrides.. but an option. @jfversluis @Redth

**Comment by jfversluis** [comment]
I think I have to agree with James. Although it's a nitty thing, I think a new method that explicitly mentions `Restricted` is a bit more discoverable and clear. 

Can we steer it to that? I think if we do that we can merge this pretty quickly. Let me know if you can do it Allan otherwise I can do it :)

**Comment by aritchie** [comment]
@jfversluis Update sent with reverted signature and new signature methods

**Review by jfversluis — APPROVED** [review]
LGTM, thanks again Allan!

**Pull request merged**
