### PR TITLE
[WIP] Merge FilePicker PRs

### LINKED ISSUE #251: Proposal : FilePicker / FolderPicker
**Description**
**FilePicker** / **FolderPicker** : nice if you add this feature
thanks

> VS bug [#735675](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735675)

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

This is a combination of PRs:
 - https://github.com/xamarin/Essentials/pull/790 _(main work by @vividos)_ ❤️
 - Bits of #613 
 - #986 _(thanks to @sung-su)_ more 💕

### Bugs Fixed ###

- Resolves #251 

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

> TODO

### Behavioral Changes ###

Should be none different, just new.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@praeclarum wondering if you could give the iOS one a look. I think you have done this before.

**Comment by EvoPulseGaming** [comment]
Just downloaded this branch and there appears to be a few issues with android file picker:
`await Permissions.RequireAsync(PermissionType.ReadExternalStorage);`
Errors:
Permissions' does not contain a definition for 'RequireAsync' (viewing Permissions.android.cs, indeed, RequireAsync does not exist)
The name 'PermissionType' does not exist in the current context

`var path = QueryContentResolverColumn(contentUri, MediaStore.Files.FileColumns.Data);`
Error:
MediaStore.Files.FileColumns.Data' is obsolete: 'deprecated'

**Comment by ChaseFlorell** [comment]
Looking forward to this PR! Great work everyone.

**Comment by Peckmore** [comment]
Apologies if this isn't the best place to raise this, but I've got PR #1194 open which adds "Save Dialog" support to the proposed file picker implementation in the _dev/file-picker branch_. However, the build for my PR is failing yet the failures don't appear to be related to the code in the PR.

I thought this could be a useful feature to include so I was hopeful it could make the cut for being merged, especially now this is targeting the 1.6.0 release. Would anyone be able to take a look or point me in the right direction as to where the problem might be?

**Comment by Redth** [comment]
@Peckmore this adds file _saving_ support then, presumably?  I'd prefer to see this in a separate PR after this one gets merged ideally.

**Comment by Peckmore** [comment]
@Redth Yeah, PR #1194 adds "Save Dialog" support to match the "Open Dialog" support of the picker implementation in this PR. It seems to go hand-in-hand so thought it would be good to implement both at the same time?

**Comment by Redth** [comment]
This is looking really good now, I think we just need one more thorough review and some testing and it's good to go!

**Comment by vividos** [comment]
Yeah I think so, too. Tizen multi-file picking is still missing, and be free to refactor code if you see fit. I can also do more PRs with change requests.

**Comment by Peckmore** [comment]
@Redth @vividos Hi both! I've finally gotten #1194 updated to the latest commits in the `dev\file-picker` branch, and all the checks are passing so, as far as I can tell, I think the SaveDialog support might also be good to go! 😄

I've also updated it to add a macOS implementation of the SaveDialog, so it's just the Tizen build now that is missing SaveDialog (and Multiple File Select) support.

If there is anything I've missed, or anything else you want me to add to the PR, let me know and I can get on it. 👍

**Comment by vividos** [comment]
It's up to the Essentials devs, I'm just a contributor :-)

**Comment by 1Cor125** [comment]
@Redth It's good to see this coming together. I notice that `PickOptions` supports `Default` and `Images`. I assume `Default` means that the picker will allow for browsing any file type whereas `Images` is a filter. Will there be a way to filter for other general types of files such as videos, etc.? Or to customize for finer-grained requirements. I noticed the [plugin](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows) that was referred to in developing this feature had something like that:

`async Task<FileData> PickFile(string[] allowedTypes = null)`

**Comment by Redth** [comment]
Yep, check the sample:

https://github.com/xamarin/Essentials/blob/develop/Samples/Samples/ViewModel/FilePickerViewModel.cs#L71-L90

**Pull request merged**
