### PR TITLE
GH-1160 Add ShouldShowRationale to Permissions API

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Add in Android implementation for ShouldShowRationale. I like the shorter name and also no need to async it.

### Bugs Fixed ###

- Related to issue #1160

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- bool Permissions.ShouldShowRationale();

### Behavioral Changes ###

none

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by mattleibow** [comment]
The code looks fine. Now we got to talk on the rationale for this... 🤣

**Comment by jamesmontemagno** [comment]
For reference: https://developer.android.com/training/permissions/requesting#explain

**Comment by Mikilll94** [comment]
@jamesmontemagno 
When Xamarin.Essentials 1.6 will be released? This feature was merged 17.04 but it is still not available.

**Comment by vividos** [comment]
@jamesmontemagno I'm a bit confused why the Permissions.ShouldShowRationale() method has the following signature:

    public static void ShouldShowRationale<TPermission>()

... while the BasePermissions definition looks like this:

    public abstract bool ShouldShowRationale();

I just wanted to use the API but stumbled over this.

**Comment by mattleibow** [comment]
Thanks for raising this. I'll check now.

**Comment by mattleibow** [comment]
Thanks for the catch @vividos, it looks to be a copy-paste issue.

I got a fix: https://github.com/xamarin/Essentials/pull/1387

A workaround for now can be to just new up the specific permission and call the instance method. I'll look at getting a preview out soon.

**Comment by vividos** [comment]
Thanks for the fix! I'll just wait for the next prerelease package.

**Comment by jamesmontemagno** [comment]
Thanks for the catch, yeah probably just a copy/paste issue originally :) that is why it is good to grab those nugets from CI to test!

**Comment by vividos** [comment]
tested with 1.6.0-pre2, and works!

**Comment by mattleibow** [comment]
Awesome! Thanks for the feedback!

**Comment by EmilAlipiev** [comment]
is that to be used only for Android? how to implement with Xamarin.forms? it will be nice to have a demo

**Comment by jamesmontemagno** [comment]
The API is cross platform and is explained here: https://docs.microsoft.com/en-us/xamarin/essentials/permissions?context=xamarin%2Fxamarin-forms&tabs=android#explain-why-permission-is-needed

**Pull request merged**
