### PR TITLE
Add .NETStandard2.0 Connectivity

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by knocte** [comment]
@lukethenuke I've proposed your improvements upstream as you can see; do you mind double-checking why CI is broken?

**Comment by danielmeza** [comment]
We should add a new ConnectionProfilefor all vpn scenarios?

**Comment by Bobface** [comment]
OpenPublishing.Build:

> Error happened in build.entrypoint.ps1.
> Please build your target branch first and then reopen this pull request to do another round of verification.
> If the issue still happens, open a ticket in https://SiteHelp and include the following error message for our team to troubleshoot:
> Cannot process argument transformation on parameter 'defaultBoolValue'. Cannot convert value "" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.

This seems to be a problem with OpenPublishing.Build. Anybody knows what that's related to?

**Comment by knocte** [comment]
> @lukethenuke I've proposed your improvements upstream as you can see; do you mind double-checking why CI is broken?

Nevermind, @Bobface fixed it.

**Comment by knocte** [comment]
Superseded by https://github.com/xamarin/Essentials/pull/1291

**Pull request closed without merging**
