### PR TITLE
[NEW PR from my Fork] Add API to retrieve directories and file lists, in a cross-platform way.

### LINKED ISSUE #1551: [Enhancement] Need for FileSystem.AppResourcesDirectory
## Summary
On _iOS_ and _macOS_ the call to **Directory.GetCurrentDirectory ()**; resolves to the **Resources** directory while on Android it just resolves to **/**.

I need all of them to resolve consistently to the **Resources** directory under _iOS_/_macOS_ and to the **Assets** folder under Android because I have a subdirectory in those locations, that vary from app to app, so I need to traverse/recurse through them to load all the required files on startup.

Now Xamarin.Essentials has **FileSystem.OpenAppPackageFileAsync**, which is great if you know the exact name of the file you want to load, but not if you want to traverse/recurse sub-directories.

## API Changes
I would like a `string FileSystem.AppResourcesDirectory` property that just resolves to **Resources** directory under _iOS_/_macOS_ and to the **Assets** folder under Android and the respective equivalents under Windows, Tizen and elsewhere.

## Intended Use Case
I need all of them to resolve consistently to the **Resources** directory under _iOS_/_macOS_ and to the **Assets** folder under Android because I have a subdirectory in those locations, that vary from app to app, so I need to traverse/recurse through them to load all the required files on startup.

If there is already a cross-platform way to do this, apologies for the waste of bandwidth :)

### PR DESCRIPTION
**Pull request by CartBlanche**
### Description of Change ###

Given a Directory name,  respectively return either the sub-directories or files within that directory

### Bugs Fixed ###

- Fixes #1551

### API Changes ###

Added: 

```csharp
public static partial class FileSystem {
    .
    .
    public string[] FileSystem.GetGetAppPackageDirectories(string path);
    public string[] FileSystem.GetGetAppPackageFiles(string path);
}
```

And associated cross-platform code.

### Behavioural Changes ###

None. New functionality.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of `main` at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### Sample UI Changes ###
**Android:**
Screenshot_1606994851

**iOS:**
Screenshot 2020-12-03 at 11 22 29

**Mac:**
Screenshot 2020-12-03 at 11 20 23

**Tizen:**
Tizen

**Windows.UWP:**
Windows

### CODE REVIEW

**Review by mattleibow — CHANGES_REQUESTED** [review]
Just linking to my original review: https://github.com/xamarin/Essentials/pull/1566#pullrequestreview-570131500

**Comment by mattleibow** [comment]
Love the new PR! Let's get this merged!

**Comment by CartBlanche** [comment]
@mattleibow Thanks for linking to your review, saves me some time.

**Comment by CartBlanche** [comment]
@mattleibow Sorry about the not replying sooner, but been busy with some other things, so not had a chance to finish this off. Should get back to it end of this week.

**Comment by CartBlanche** [comment]
Closing as it's been SOO long and branches have diverged and a new and cleaner PR will be incoming.

**Comment by CartBlanche** [comment]
Updated PR which address the points from in the initial review is now here - https://github.com/xamarin/Essentials/pull/1886

**Pull request closed without merging**
