### PR TITLE
Add `ColorConverters.GetCompliment()` method

### PR DESCRIPTION
**Pull request by mrlacey**
### Description of Change ### 

Add ability to easily get a complimentary color to the ColorConverters class.

No samples added as nothing else in this [helper] class has samples.

### Bugs Fixed ###

- Related to issue #957 

### API Changes ###

Added: 
 
- `public static Color GetCompliment(Color original)`

### Behavioral Changes ###

none

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by mrlacey** [comment]
**Notes on build failure**

> Please follow instructions here which may help to resolve issue.

The **here** mentioned above is to a location (https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master) that I don't have access to.

- The Details links in the table listing issues don't go anywhere useful.

- `_dependentPackages/ECMA2Yaml/tools/Run.ps1` and `.openpublishing.publish.config.json` do not contain any changes by me and have nothing specific to the changes I've made.

- The [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C4%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201911041222004314-970%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6qMW4QA5X57eMfHMM%2FsdAkdKH4Np2g6iSpE29Sca85E%3D&st=2019-11-04T12%3A17%3A44Z&se=2019-12-05T12%3A22%3A44Z&sp=r) contains errors and warnings related to things I haven't changed. This looks like an issue unrelated to my PR and so don't know what I can do to address the problem myself.

Advice on what (if anything) I can do to address the above will be appreciated.

**Comment by jamesmontemagno** [comment]
@praeclarum any thoughts on this? I know you did a bunch of color compliment stuff on Continuous.

**Comment by praeclarum** [comment]
Yeah, this converts the color to its opposite hue. Pretty standard and useful in a jiffy.

This does not provide dark/light compliments like Continuous has, just the hue compliment.

**Comment by jamesmontemagno** [comment]
@praeclarum do you think the name is appropriate?

**Comment by attrib75** [comment]
Idea:  This thread is a great example of how the community can see how things get built at MS and what the process is so that we may feel less intimidated by it and contribute more.   It would be awesome if you guys made a video touching on the kinds of things that happened here.  PR > build pipelines > checkins, dicusssions, approval, merge, etc.  Maybe you already do and I'm not aware of it.

**Comment by vividos** [comment]
I'm not a native English speaker, but I'm pretty sure Compliment is not the correct term, is complement or complementary.
Ah, here's a page explaining the difference: https://www.lawlessenglish.com/english-mistakes/complement-vs-compliment/

**Comment by jamesmontemagno** [comment]
Great catch! I think Complementary is correct to use :)

**Comment by mrlacey** [comment]
@jamesmontemagno should I open a new issue for the rename or will you reopen the original one for this PR (#957)

**Comment by jamesmontemagno** [comment]
Feel free to open a new PR :) I opened an issue for it

**Pull request merged**
