### PR TITLE
Fix parameters order bug on Location. CalculateDistance() call.

### PR DESCRIPTION
**Pull request by ncarandini**
### Description of Change ###
I've simply changed the order of the parameters in the call of the CalculateDistance(…).

### Bugs Fixed ###
Now the CalculateDistance(Location locationStart, Location locationEnd, DistanceUnits units) returns correct values.

- Related to issue #306

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [x] Has tests: not needed, it's a straightforward bug fix
- [x] Has samples: not needed
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation: no documentation change needed

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
build

**Comment by ncarandini** [comment]
Hi @jamesmontemagno, **build** is something related to the CI process or something that I have to do?

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/Types/Location.shared.cs](https://github.com/ncarandini/Essentials/blob/master/Xamarin.Essentials/Types/Location.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806251447166192-307%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uFotXioyhW0w6ZeusSteYogiDd3RsrwXQngCuRSS5yk%3D&st=2018-06-25T14%3A43%3A16Z&se=2018-07-26T14%3A48%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Redth** [comment]
Thanks for this!

**Pull request merged**
