### PR TITLE
GH-254 Update Support Packages, Forms, and Reference Vectors

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Update Support Packages, Forms, and Reference Vectors

### Bugs Fixed ###

- Related to issue #254 

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- string - string Class.Property { get; set; } 
- void Class.Method();

Changed:

 - object Cell.OldPropertyName => object Cell.NewPropertyName

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Samples.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Samples.Android.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.UWP/Samples.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.UWP/Samples.UWP.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.iOS/Samples.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.iOS/Samples.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples/Samples.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples/Samples.csproj) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C5%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806051752530236-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qKE%2FFefCu6dSzTUuXqL1l1Lk17CFIW3uXPsF385kl8M%3D&st=2018-06-05T17%3A48%3A54Z&se=2018-07-06T17%3A53%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
build

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Samples.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Samples.Android.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.UWP/Samples.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.UWP/Samples.UWP.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.iOS/Samples.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.iOS/Samples.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples/Samples.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples/Samples.csproj) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C5%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806051804413984-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=22K5xMgCdcWFdvfKzyfHR9iim66dJRdmWVLTHuw1fnc%3D&st=2018-06-05T18%3A00%3A36Z&se=2018-07-06T18%3A05%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Samples.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Samples.Android.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.UWP/Samples.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.UWP/Samples.UWP.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.iOS/Samples.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.iOS/Samples.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples/Samples.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples/Samples.csproj) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C5%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806051818030738-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FcpXYQNImqtuVBRbnlARqr1RFnTo5a8vzvCk96GB2vA%3D&st=2018-06-05T18%3A13%3A58Z&se=2018-07-06T18%3A18%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Samples.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Samples.Android.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.UWP/Samples.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.UWP/Samples.UWP.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.iOS/Samples.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.iOS/Samples.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples/Samples.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples/Samples.csproj) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Vibration/Vibration.android.cs](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Vibration/Vibration.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C5%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806051827556760-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0oBj6hn9h6gQe%2FH%2BQ4geC8pOOuEy8UsHgwnVDkOFL3U%3D&st=2018-06-05T18%3A23%3A50Z&se=2018-07-06T18%3A28%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Samples.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Samples.Android.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.UWP/Samples.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.UWP/Samples.UWP.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.iOS/Samples.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.iOS/Samples.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples/Samples.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples/Samples.csproj) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Vibration/Vibration.android.cs](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Vibration/Vibration.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C5%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806051921371333-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qKz4hcgLsxLcm8MzuBiJkwPDfS51lAFkeHLJAPP%2B8mo%3D&st=2018-06-05T19%3A17%3A44Z&se=2018-07-06T19%3A22%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Properties/AndroidManifest.xml](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Properties/AndroidManifest.xml) | :white_check_mark:Succeeded | |
[Samples/Samples.Android/Samples.Android.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.Android/Samples.Android.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.UWP/Samples.UWP.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.UWP/Samples.UWP.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples.iOS/Samples.iOS.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples.iOS/Samples.iOS.csproj) | :white_check_mark:Succeeded | |
[Samples/Samples/Samples.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Samples/Samples/Samples.csproj) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Vibration/Vibration.android.cs](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Vibration/Vibration.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/bug/issue-254/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C7%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806071709083707-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NhXZYLvFONDyxQfIT84JUr3PZPDB89PCAD8gol%2BuEWQ%3D&st=2018-06-07T17%3A05%3A19Z&se=2018-07-08T17%3A10%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
build

**Comment by jamesmontemagno** [comment]
weird that adb wasn't running... maybe we should do an adb start-server??

**Pull request merged**
