### PR TITLE
Added "SaveDialog" support to FilePicker class.

### PR DESCRIPTION
**Pull request by Peckmore**
### Description of Change ###

- Implemented `PickFileToSaveAsync` for iOS, Android, UWP, macOS, and throw `NotImplementedInReferenceAssemblyException` for Tizen, .Net Standard, tvOS, watchOS.
- Added `SuggestedFileName` to `PickOptions` to suggest a default file name when saving.
- Added `OpenWriteStreamAsync` to `FilePickerResult` to open a file for writing.
- Changed the iOS picker to _Open_ a file instead of _Import_ a file to prevent read stream locks when trying to open a write stream.
- Added Android support for `Intent.ActionOpenDocument`.
- Added `PickMultipleFilesAsync()` overload to call without specifying `PickOptions` (for consistency with `PickFileAsync()`).

### Bugs Fixed ###

- Related to issue #251, #975, #613, #790

### API Changes ###

Added: 
 
**FilePicker**
- `public static Task<FilePickerResult> PickFileToSaveAsync()`
- `public static Task<FilePickerResult> PickFileToSaveAsync(PickOptions options)`
- `public static Task<IEnumerable<FilePickerResult>> PickMultipleFilesAsync()`

**PickOptions**
- `public string SuggestedFileName { get; set; }`

**FilePickerResult**
- `public Task<Stream> OpenWriteStreamAsync()`

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by Peckmore** [comment]
Wonder if anyone might be able to lend an assist or shed some light on the failing checks? It looks like the iOS Tests are failing to even start, but doesn't look related to the commit/PR? Or have I missed something?! :)

**Comment by sps014** [comment]
My two test cases are also failing with a totally unrelated error, don't have any clue about it ,xamarin team need to sort it out.

https://github.com/xamarin/Essentials/pull/1196

**Comment by Redth** [comment]
@Peckmore could you rebase this on the latest commit to the `dev/file-picker` branch?

**Comment by Peckmore** [comment]
@Redth Apologies for not spotting this sooner - I'll get onto this today!

**Comment by Peckmore** [comment]
@Redth I've updated my fork to the latest commit from the `dev/file-picker` branch, and also updated my PR to include a macOS implementation of the FilePicker Save Dialog.

However, the build is now failing because the `BasePlatformImplementation` for macOS does not implement `ShouldShowRationale()`. I will add it in, to see if that gets the build to pass, but not sure if it's meant to be missing, or I've gotten something wrong in my fork?

**Comment by Peckmore** [comment]
I've added an implementation of `ShouldShowRationale()` into `BlasePlatformImplementation` in `Permissions.macos.cs` - not sure if this is the right thing to do, but it was missing and needed? Everything seems to build correctly and all checks pass now however. 😄

**Comment by Peckmore** [comment]
@Redth Would you like me to resubmit this against the `develop` branch? Or will save dialog support not make the cut? :)

**Comment by mattleibow** [comment]
I think this may have been a bad close. Can you reopen and rebase this or is it easier to open a new PR? Not sure how bad the conflicts are...

**Comment by Peckmore** [comment]
@mattleibow I'll reopen and rebase it, see how that goes! 😁

**Comment by Rabosa616** [comment]
Any news?

**Pull request closed without merging**
