### PR TITLE
Fix failing auth redirect on Android

### LINKED ISSUE #2070: [Bug] Xamarin Essentials Web Authenticator & Open Browser
### Description
For reference:

    https://learn.microsoft.com/en-us/xamarin/essentials/open-browser?context=xamarin%2Fandroid&tabs=android
    https://learn.microsoft.com/en-us/xamarin/essentials/web-authenticator?context=xamarin%2Fandroid&tabs=android

I am using both of these features and everything works as expected when I was on an emulator that targeted android 11. It was working without adding the recommended configurations from the documentation above.

when the app is run on an emulator that targets android 13, neither of these features works anymore. the browser just opens and never finished loading the page. If the browser is closed the app will recognize a cancel method was called.

from the documentation, I have tried with and without the configurations and to no avail.

```
<queries>
        <intent>
        <action android:name="android.support.customtabs.action.CustomTabsService" />
    </intent>
        <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="http"/>
  </intent>
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="https"/>
  </intent>
    </queries>

```

My original SO question was confirmed by MSFT - https://stackoverflow.com/questions/75011446/xamarin-essentials-web-authenticator-open-browser

### Steps to Reproduce

1.  Launch Xamarin Forms app
2.  Click Button web authentication or a browser
3.  they both just hang

### Expected Behavior

Open the Browser on target android 13

### Actual Behavior

the Browser just hangs on target android 13

### Basic Information

- Version with issue: 1.7.4
- Last known good version:
- IDE: VS 2022
- Platform Target Frameworks: 
  - iOS:  
  - Android: Android 13 
  - UWP:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

image

### LINKED ISSUE #2081: Web Authenticator not returning back to App in Android 12, when user sharing(Intent.ActionSend)
**Description:**

We developed a mobile app, where users can share documents and pictures from Mobile App. 

When user shares a picture/document with our Mobile App, the app will ask the user to log in. We are using WebAuthenticator to login and logout from our app.

Once the login has been made, from the browser it is not redirected back to the APP. We found it is happening only on Android devices, and when we are sharing, the Intent action will be Intent.ActionSend

**Steps to Reproduce**

1. Create a sample content page with a button(let's call it as login button).
2. In MainActivity.cs -> Add a code to support sharing -> [[IntentFilter(new[] { Intent.ActionSend }, Categories = new[] { Intent.CategoryDefault }, DataMimeTypes = new[] 
    {  
       "image/*",
       "image/bmp",
       "image/jpg",
       "image/png",
       "text/plain",
       "application/vnd.oasis.opendocument.text",
       "application/vnd.oasis.opendocument.image",
       "application/vnd.ms-excel",
       "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
       "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
       "application/msword",
       "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
       "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
       "application/pdf", 
       "application/vnd.ms-powerpoint", 
       "application/vnd.openxmlformats-officedocument.presentationml.presentation",
       "application/vnd.openxmlformats-officedocument.presentationml.template",
       "video/*",
       "video/mp4"
      
        })]]
3. On login button click, add a code for the web authenticator something like the below:
 [ await WebAuthenticator.AuthenticateAsync(new WebAuthenticatorOptions
			{
				Url = new Uri($"{_baseUrl}/auth/mobile"),
				CallbackUrl = new Uri("trimapp://")
			});]
4. Open your gallery, share any image -> Select the app you have developed. It will show an login button 
5. Click on the login button -> Web authenticator will take you to the chrome browser to login to the app.
6. After the successful login, it is not getting redirected to the APP.

### Expected Behavior
App should be redirected without any issues.

### Actual Behavior
App stays in browser page, but in background i can see the Application instance got opened, but the redirection was not happening.
### Basic Information

- Version with issue:
- Last known good version: Android 11
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: 1.7.0(Xamarin.Essentials)
- Affected Devices: Android 12

### PR DESCRIPTION
**Pull request by jfversluis**
* Maybe fixes #2070
* Maybe fixes #2081

### CODE REVIEW

**Comment by ekeneduru** [comment]
Which nuget version should i try

**Comment by ekeneduru** [comment]
Please how do i go about this?

**Comment by jfversluis** [comment]
@ekeneduru please go to https://dev.azure.com/xamarin/public/_build/results?buildId=87948&view=results

And find the artifact, it's shown as "8 published; 2 consumed", click that and then click "nuget", that will get you the NuGet locally.

image

This process is also shown here, including how to add a NuGet package from a local folder on your machine: https://blog.verslu.is/xamarin-forms-xamarin/test-xamarin-forms-bugfixes/#how-to-test-today

**Comment by ekeneduru** [comment]
Not working. Still stuck in the facebook url page that have the token. is not taking me back to the app.

**Comment by CelloLiu** [comment]
I'm having the same issue on google emulator and pixel 7 pro, it shows the token related info on a page and cannot redirect back to my blazor hybrid mobile app based on .net 8

**Pull request merged**
