### PR TITLE
Update Readme with Installation information.

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Update Readme!

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[README.md](https://github.com/xamarin/Essentials/blob/update-install/README.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C10%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805100158141434-237%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7v8F1yqzZxmagSGuuSlquhQh%2FXT40FZeMu67D2%2BjL%2BQ%3D&st=2018-05-10T01%3A54%3A07Z&se=2018-06-10T01%3A59%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[README.md](https://github.com/xamarin/Essentials/blob/update-install/README.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C10%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805100159099243-237%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bV2KQTuNSdZNzrVigcs4KdunznyR9Qu571AM9G8vUa0%3D&st=2018-05-10T01%3A55%3A03Z&se=2018-06-10T02%3A00%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[README.md](https://github.com/xamarin/Essentials/blob/update-install/README.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C10%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805100200371595-237%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vCIBo902XG0SCQaLV5bIzeCehxRzeMj2fWbr%2B1%2F3hFs%3D&st=2018-05-10T01%3A56%3A33Z&se=2018-06-10T02%3A01%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
build

**Pull request merged**
