### PR TITLE
GH-380 Use Internal Preferences for Secure Storage consistency.

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Use Internal Preferences for Secure Storage consistency.
Save if we created key pre-M so we always use pre-M if device upgrades.

### Bugs Fixed ###

- Related to issue #380

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

No API changes, only internal.

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807171644014295-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YZWelNFd1j9p3A4CsU4mjxoa0W82brigiXmZuGFQbvU%3D&st=2018-07-17T16%3A39%3A57Z&se=2018-08-17T16%3A44%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807172005163794-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zGA2qiwGztwzqcH6pq4a9gwPnjLH6fFDX4rXx0%2FfpPE%3D&st=2018-07-17T20%3A01%3A14Z&se=2018-08-17T20%3A06%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807172117482774-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XuPpNeyeh8bP231qr9oBG5cX1Lcsn4UBg4Xpp7K%2BcXo%3D&st=2018-07-17T21%3A13%3A45Z&se=2018-08-17T21%3A18%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807181611504904-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YOiTU91qxWGdw2z3KU2n0t9%2F5iDlzNIsOHutnn8MLV4%3D&st=2018-07-18T16%3A07%3A48Z&se=2018-08-18T16%3A12%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
@mattleibow updated!

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807191942130636-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wEo7nvh8h4B1xwE2VRAWyF5Izw%2BDTJ7iz%2FbmHR8DbZg%3D&st=2018-07-19T19%3A38%3A10Z&se=2018-08-19T19%3A43%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807192003400646-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=I%2BQODi32u5Z%2BwfmYsCDm8rD2%2BI1x5YLKFUW4ncZ8C5s%3D&st=2018-07-19T19%3A59%3A38Z&se=2018-08-19T20%3A04%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807192018031501-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IWBMVzNqY6Wir5%2FJY3Z0de517jjWgU3rY47WMbFWdkM%3D&st=2018-07-19T20%3A14%3A00Z&se=2018-08-19T20%3A19%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807192040300557-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gXoDhmBtzeoipDN%2BvRm57cCf4A0xa9cqMyGdTxgG6XA%3D&st=2018-07-19T20%3A36%3A30Z&se=2018-08-19T20%3A41%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
build

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/SecureStorage/SecureStorage.android.cs](https://github.com/xamarin/Essentials/blob/bug/secure-storage-enhancements/Xamarin.Essentials/SecureStorage/SecureStorage.android.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C20%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807201548574636-386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iTTG4Mzi36ZTRZPU2Ncl9gottckLNV4gHEZ8V5NcWC0%3D&st=2018-07-20T15%3A44%3A55Z&se=2018-08-20T15%3A49%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
