### PR TITLE
Feature/GH-178 Record Audio

### PR DESCRIPTION
**Pull request by Mrnikbobjeff**
### Description of Change ###
Added audio recording capabilities to Essentials
- Related to issue #178
### API Changes ###

Added: 

```csharp
public static class Recorder
{
        public static Task<bool> CanRecordAudio => PlatformCanRecordAudio;

        public static bool IsRecording { get; private set; }

        public static async Task RecordAsync();

        public static async Task<RecordedAudio> StopAsync()
}

public class RecordedAudio : IDisposable
{
        public Stream AsStream();
        public string Filepath {get;}
}
```

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by Mrnikbobjeff** [comment]
I based it on the dev/1.1.0 branch.  Tested on UWP, will test it on Android tonight. It will not present an issue when submitted to the store as I claimed in the original ticket.

**Comment by mattleibow** [comment]
@jamesmontemagno @Redth This is 100% another reason we need to get  https://github.com/xamarin/Essentials/pull/613 merged (and related). Then we need to go though and make all the variants in different areas work the same. See the comments in that PR

**Comment by Mrnikbobjeff** [comment]
I rebased it ontop of the branch containing the FileBase class and used it as base class for audio recording. Also added unit tests and made the Android implementation work. I still need to test iOS but I need to set up a certificate first. Otherwise I'd love some feedback on the recording class and the uwp and android implementation as I'd love to have this merged soon to be used in production for an application we are developing :)

**Comment by Mrnikbobjeff** [comment]
@newky2k @mattleibow I adressed the documentation issue and included the changes requested toward file storage location you suggested matt, would be wonderful if this could be reviewed again :)

**Comment by Mrnikbobjeff** [comment]
Are there any plans to finally include this branch into the upcoming release? There has been virtually no developement on this branch except deciding where to store the file in the last 8 months. We are already rolling our own EssentialsEx package including this and other branches which remained virtually finished for quite a while. @jamesmontemagno @mattleibow

**Comment by domagojmedo** [comment]
This PR is almost 2 years old, is there any point in keeping this open if it's not getting merged?

@jamesmontemagno

**Comment by mattiascibien** [comment]
This is actually something we may need in our project to delete our custom based handling

**Comment by jfversluis** [comment]
> This PR is almost 2 years old, is there any point in keeping this open if it's not getting merged?
> 
> @jamesmontemagno

We had to wait until 3 years! Closing this now. If this is still something you would like to see, please open an issue on the .NET MAUI repo. Thanks!

**Comment by jfversluis** [comment]
And of course thank you so, so much for your work on this @Mrnikbobjeff hopefully we will be able to salvage the code for .NET MAUI. I'm sorry this didn't make it in for now.

**Pull request closed without merging**
