### PR TITLE
Remove launch adjacent Fixes #2023

### LINKED ISSUE #2023: [Bug] Launcher: Pixel 4 or newer, Android 12 forces split screen when opening files with default app
### Description
On Pixel 4 devices or newer with Android 12, if a file is opened using `Launcher.OpenAsync()` the file is opened in split screen mode adjacent to the source app regardless of whether `android:resizeableActivity` is `false` in the manifest file.

The issue is that when it goes into split screen mode the source app is reloaded and any in-progress state is lost in that app.

I've narrowed the problem down to the following logic in the `PlatformOpenAsync()` method of the `Launcher.android.cs` file:

`#if __ANDROID_24__
            if (Platform.HasApiLevelN)
                flags |= ActivityFlags.LaunchAdjacent;
#endif`

Removing this logic fixes the issue.

### Steps to Reproduce

1. Deploy your Xamarin App to a Pixel 4 or newer device
2. Open a PDF or DOCX file from your Xamarin App using `Launcher`

### Expected Behavior
PDF or DOCX file should be opened in a new window and the source app state should remain as before if `android:resizeableActivity` is `false`

### Actual Behavior
PDF or DOCX file is open adjacent in split screen mode and the source app is reloaded, losing any in-progress state

### Basic Information

- Version with issue:
- Nuget Packages: Xamarin.Forms 5.0.0.2012, Xamarin.Essentials 1.7.1
- Affected Devices: Pixel 4a, Pixel 5

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

We shouldn't do this. Browser has an option

### Bugs Fixed ###

- Related to issue #2023

### CODE REVIEW

**Comment by andreasbrostencab** [comment]
Any reason why no one is reviewing this?

**Review by jfversluis — APPROVED** [review]

**Comment by Bejasc** [comment]
When can 1.7.4 be expected with this fix? 
In the meantime - is there a workaround?

**Comment by nikolajskov** [comment]
> When can 1.7.4 be expected with this fix? In the meantime - is there a workaround?

I'm also waiting for the next release with a fix for this. In the meantime, I've stopped using the Xamarin Essentials Launcher and am using my own implementation without the LaunchAdjacent flag for now.

**Comment by jamesmontemagno** [comment]
Fixes #2007

**Comment by shnaz** [comment]
We have exact same problem which should be fixed by this.

@jfversluis I see the 1.7.4 was released 3 days ago, according to https://github.com/xamarin/Essentials/releases/tag/1.7.4.

But it is not updated in nuget.org, is this intentional and why?
https://www.nuget.org/packages/Xamarin.Essentials

**Comment by jamesmontemagno** [comment]
I think we had some CI/CD problems, should hopefully be fixed soon.

**Pull request merged**
