### PR TITLE
Make sure that there is always a valid Intent

### LINKED ISSUE #1397: [Bug] NullReferenceException is thrown after CapturePhotoAsync
### Description
A NullReferenceException is thrown after taking a picture with CapturePhotoAsync. The camera app is shown, a picture can be taken. But after accepting the picture the error occurs.

### Steps to Reproduce

1. Take a picture
2. Accept the picture
3. NullReferenceException is thrown from Xamarin.Essentials

09-28 09:30:51.173 I/MonoDroid( 2663): UNHANDLED EXCEPTION:
09-28 09:30:51.175 I/MonoDroid( 2663): System.NullReferenceException: Object reference not set to an instance of an object.
09-28 09:30:51.175 I/MonoDroid( 2663):   at Xamarin.Essentials.IntermediateActivity.OnActivityResult (System.Int32 requestCode, Android.App.Result resultCode, Android.Content.Intent data) [0x00041] in D:\a\1\s\Xamarin.Essentials\Platform\Platform.android.cs:458 
09-28 09:30:51.175 I/MonoDroid( 2663):   at Android.App.Activity.n_OnActivityResult_IILandroid_content_Intent_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 requestCode, System.Int32 native_resultCode, System.IntPtr native_data) [0x00013] in /Users/builder/azdo/_work/287/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-28/mcw/Android.App.Activity.cs:2373 
09-28 09:30:51.175 I/MonoDroid( 2663):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.8(intptr,intptr,int,int,intptr)

### Expected Behavior
Picture is selected without exception

### Actual Behavior
NullReferenceException is thrown.

### Basic Information

- Version with issue: 1.6.0-pre2
- Last known good version: NA
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:   NA
  - Android:  Android 10.0
  - UWP:   NA
- Android Support Library Version:  NA
- Nuget Packages:
- Affected Devices: Motorola AOSP on shama (Android 5.1 - API 22) (on nox emulator)

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

Make sure that there is always a valid Intent when the intermediate activity returns.

### Bugs Fixed ###

- Fixes #1397

### API Changes ###

None.

### Behavioral Changes ###

If the intent is null, then create one and not crash.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of `main` at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by mattleibow** [comment]
@Mrnikbobjeff Thanks for the research. I did not include the check for the `resultCode` in this PR as I am unsure what the side effects will be. I can do that in a new PR and after a few tests.

**Comment by Mrnikbobjeff** [comment]
I was also unsure about the side effects. Because I could not verify the behaviour I also would use the compatible version which does not check the result code. According to the documentation this does appear to be a valid guard though :)

**Comment by mattleibow** [comment]
There that "FirstUser" option as well. I'll have a look at this, but I suppose in the meantime the nuget can be checked by anyone with a dodgy device.

**Comment by zunjae** [comment]
Issue persists on 1480.1 on release builds on real devices

**Comment by zunjae** [comment]
@mattleibow how can we test this branch? I can't seem to figure out how to make NuGet pull this fix

**Comment by Mrnikbobjeff** [comment]
> I pushed the PR build to the preview feed so hopefully there can be a test.
> 
> Feed: `https://aka.ms/xamarin-ci/index.json`
> Version: `1.6.0-pr.1480.1`

Quoting mat from the issue linked to this pr. Simply add the link to your budget.json or if you build from within Vs you can also add the package source there

**Comment by zunjae** [comment]
@Mrnikbobjeff I have no idea what a budget.json is, a Google search doesn't help either. I've added the link as source in the Package Sources tab, however, when opening the NuGet Package Manager and searching all all packages (including pre-releases), I only see "Microsoft.Azure.Mobile.Client" and "Microsoft.Azure.Mobile.Client.SQLiteStore".

Is the branch already live or do I need to wait?

**Comment by Mrnikbobjeff** [comment]
Yeesh, mobile autocorrect changed nuget.json to budget.json. just follow the guide https://docs.telerik.com/reporting/add-the-telerik-private-nuget-feed-to-visual-studio
But use the posted URL instead of the one used in the manual

**Comment by zunjae** [comment]
image

@Mrnikbobjeff Yeah I've done that... Still unable to see Xamarin.Essentials

**Comment by mattleibow** [comment]
@zunjae terribly sorry, I think I pasted the wrong URL to the feed. I was working with both and then mixed them up... I wonder what I sent to the other team 😬 

The correct feed is https://nugetized.blob.core.windows.net/xamarin-essentials-nightly/index.json

**Pull request merged**
