### PR TITLE
Implement vertical accuracy in GeoLocation API

### PR DESCRIPTION
**Pull request by janusw**
### Description of Change ###

This extends the GeoLocation API to provide the vertical accuracy.

### Bugs Fixed ###

- Related to issue #1099

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- `double? Location.VerticalAccuracy { get; set; }`

Changed:

 - None
 

### Behavioral Changes ###

None.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard
- [X] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by Redth** [comment]
Question about the value on each platform.  Are we sure this is accuracy in meters on iOS, Android and UWP?  Just want to double check we don't need any code to normalize values here.

**Comment by janusw** [comment]
> Question about the value on each platform. Are we sure this is accuracy in meters on iOS, Android and UWP?

Yes, the links to the documentation of the API calls on each platform can be found in #1099. All three explicitly mention that the returned value is in meters.

**Comment by janusw** [comment]
@Redth Thanks for the approval! Any chance to still get this into the 1.5.0 release?

**Comment by Redth** [comment]
Yes I think we can put this into 1.5 still

**Comment by janusw** [comment]
Thanks a lot for merging!

Unfortunately I discovered just in this very moment a problem with older Android versions: The compile-time check does not seem to be sufficient, and we'll need a runtime check in addition :/

Sorry about that. I'll open a follow-up PR with the fix shortly!

**Pull request merged**
