### PR TITLE
Added the notifications API

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

Was bored so I whipped this up this weekend. I think Android is correct as it works on my v5.0 and my v8.1. UWP is finished. I just coded the iOS so it builds.

The API just came to me, so it will need a total review from scratch.

### Bugs Fixed ###

- Related to issues #238 #516 

### API Changes ###

```csharp
public static class Notifications {
    // show
    public static void Show(string description);
    public static void Show(string title, string description);
    public static void Show(int id, string title, string description);
    public static void Show(Notification notification);

    // cancel
    public static void Cancel(int notificationId);
    public static void Cancel(Notification notification);
    public static void CancelAll();
}
```

```csharp
public class Notification {
    public Notification();
    public Notification(string description);
    public Notification(string title, string description);
    public Notification(int id, string title, string description);

    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }

#if __ANDROID__
    // required, but falls back to "ic_dialog_info"
    public static int SmallIconResource { get; set; }

    // required for API 26, but falls back to "xamarinessentials"
    public static string ChannelName { get; set; }

    // optional for API 26
    public static string ChannelDescription { get; set; }
#endif
}
```

### Behavioral Changes ###

New API.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Samples/Samples/View/NotificationsPage.xaml](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Samples/Samples/View/NotificationsPage.xaml) | :white_check_mark:Succeeded | |
[Samples/Samples/View/NotificationsPage.xaml.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Samples/Samples/View/NotificationsPage.xaml.cs) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/HomeViewModel.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Samples/Samples/ViewModel/HomeViewModel.cs) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/NotificationsViewModel.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Samples/Samples/ViewModel/NotificationsViewModel.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Notifications/Notifications.android.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Xamarin.Essentials/Notifications/Notifications.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Notifications/Notifications.ios.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Xamarin.Essentials/Notifications/Notifications.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Notifications/Notifications.netstandard.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Xamarin.Essentials/Notifications/Notifications.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Notifications/Notifications.shared.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Xamarin.Essentials/Notifications/Notifications.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Notifications/Notifications.uwp.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Xamarin.Essentials/Notifications/Notifications.uwp.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Permissions/Permissions.ios.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Xamarin.Essentials/Permissions/Permissions.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Permissions/Permissions.shared.enums.cs](https://github.com/xamarin/Essentials/blob/feature/local-notifications/Xamarin.Essentials/Permissions/Permissions.shared.enums.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C24%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201809240008079317-518%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=M8i8k36t9J2ZqgX8uE21ECp%2FAsK%2Ft7rcuTVysdbITPk%3D&st=2018-09-24T00%3A04%3A19Z&se=2018-10-25T00%3A09%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Essentials/issues/516#issuecomment-435228118

**Comment by Rivolvan** [comment]
Thanks. Read that comment and I also understand the reasoning. But the comment also said that:

> If you see #518 this is more likely to be included because it leverages UI bits that each platform already uses for displaying notifications, and therefore doesn't require custom UI.

If it is more likely to be included, will this be merged in the near future after some deliberation? Thank you

**Comment by Redth** [comment]
We don't have any ETA for these features. But I think local notifications will be worked on closely in time with any other features requiring background tasks since there won't be much you can really do with background tasks except send something to a server or send a local notification to let the user decide if they want to act on whatever happened in the background task.

**Pull request closed without merging**
