### PR TITLE
Fix crash of clipboard sample when text is null

### PR DESCRIPTION
**Pull request by bares43**
### Description of Change ###
This fixes crash of clipboard sample when text is null.

### API Changes ###
None

### Behavioral Changes ###

Sample app doesn't crash anymore.

### PR Checklist ###

- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
I am thinking null == string.empty :)

**Comment by bares43** [comment]
Thanks for your review and reply.

Actually, I'm not sure what you mean by empty string. Do you mean add here https://github.com/xamarin/Essentials/blob/develop/Xamarin.Essentials/Clipboard/Clipboard.shared.cs#L9m something like this?
`
if (text == null)
{
    text = string.Empty;
}
`

In that case user would end up with empty string in the clipboard. [http://prntscr.com/tumh6s](http://prntscr.com/tumh6s)

Maybe it would be better to call return, when string is null. Like this:
`
if (text == null)
{
    return Task.FromResult<object>(null);
}
`

What do you think?

**Comment by mattleibow** [comment]
Setting an empty or null might be a way to clear the clipboard... I think that might be a nice feature.

**Comment by jamesmontemagno** [comment]
If you set string.Empty it will clear it, so probably if you pass in null it should just set it to string.Empty for you... or throw an exception lol

**Comment by mattleibow** [comment]
Maybe for the sample, pass in "" if it is null, but for the actual API, throw?

**Comment by jamesmontemagno** [comment]
i think converting it to "" is ideal

**Comment by bares43** [comment]
Ok, so as I wrote above, I will just set `string.Empty` if value is `null` in `Clipboard.shared.cs`.

**Comment by bares43** [comment]
I guess that since this PR is already merged, I don't have to change anything. Or do you think I should create another PR and add `string.Empty` to `Clipboard.share.cs` whent it's `null`? @jamesmontemagno @mattleibow

**Comment by mattleibow** [comment]
Could you create a new PR for that? It would be awesome!

**Comment by bares43** [comment]
> Could you create a new PR for that? It would be awesome! 

Sure :)

**Comment by bares43** [comment]
New PR is here #1345

**Pull request merged**
