### PR TITLE
Name Alignment for BrowserLaunchMode

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

BrowserLaunchType should really be BrowserLaunchMode to sync with other enums.

Only other is "DeviceType", which is accurate.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Samples/Samples/View/BrowserPage.xaml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Samples/Samples/View/BrowserPage.xaml) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/BrowserViewModel.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Samples/Samples/ViewModel/BrowserViewModel.cs) | :white_check_mark:Succeeded | |
[Tests/Browser_Tests.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Tests/Browser_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.netstandard.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.uwp.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.uwp.cs) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/Browser.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/Xamarin.Essentials/Browser.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/BrowserLaunchMode.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/Xamarin.Essentials/BrowserLaunchMode.xml) | :white_check_mark:Succeeded | |
[docs/en/index.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/index.xml) | :white_check_mark:Succeeded | |
[nugetreadme.txt](https://github.com/xamarin/Essentials/blob/bug/name-alignment/nugetreadme.txt) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C24%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807242152463186-408%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bjDuXNZU%2B5sKpzGUkvVAy2HuTkV2l5PC1Oj7gkEFRyo%3D&st=2018-07-24T21%3A49%3A05Z&se=2018-08-24T21%3A54%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Samples/Samples/View/BrowserPage.xaml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Samples/Samples/View/BrowserPage.xaml) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/BrowserViewModel.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Samples/Samples/ViewModel/BrowserViewModel.cs) | :white_check_mark:Succeeded | |
[Tests/Browser_Tests.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Tests/Browser_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.netstandard.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.uwp.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.uwp.cs) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/Browser.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/Xamarin.Essentials/Browser.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/BrowserLaunchMode.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/Xamarin.Essentials/BrowserLaunchMode.xml) | :white_check_mark:Succeeded | |
[docs/en/index.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/index.xml) | :white_check_mark:Succeeded | |
[nugetreadme.txt](https://github.com/xamarin/Essentials/blob/bug/name-alignment/nugetreadme.txt) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807251536364116-408%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MUBStxhWqC5xSOJmOs2W8ARYSb3v%2FTAvY7VR3h93ai0%3D&st=2018-07-25T15%3A32%3A51Z&se=2018-08-25T15%3A37%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Samples/Samples/View/BrowserPage.xaml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Samples/Samples/View/BrowserPage.xaml) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/BrowserViewModel.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Samples/Samples/ViewModel/BrowserViewModel.cs) | :white_check_mark:Succeeded | |
[Tests/Browser_Tests.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Tests/Browser_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.netstandard.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.uwp.cs](https://github.com/xamarin/Essentials/blob/bug/name-alignment/Xamarin.Essentials/Browser/Browser.uwp.cs) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/Browser.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/Xamarin.Essentials/Browser.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/BrowserLaunchMode.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/Xamarin.Essentials/BrowserLaunchMode.xml) | :white_check_mark:Succeeded | |
[docs/en/index.xml](https://github.com/xamarin/Essentials/blob/bug/name-alignment/docs/en/index.xml) | :white_check_mark:Succeeded | |
[nugetreadme.txt](https://github.com/xamarin/Essentials/blob/bug/name-alignment/nugetreadme.txt) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807251557226214-408%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4UpNUNLEVq9DCFUi28YcHIE352edXEsBmdK0C1XRzfg%3D&st=2018-07-25T15%3A53%3A32Z&se=2018-08-25T15%3A58%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
Should be good now, renamed the parameter too :)

**Pull request merged**
