### PR TITLE
fix the typo from Chanaged toChanged

### PR DESCRIPTION
**Pull request by Powerhelmsman**
Fix the typo from ScreenMetricsChanagedEventArgs to ScreenMetricsChangedEventArgs

### Description of Change ###

Describe your changes here. 

### Bugs Fixed ###

- Related to issue #

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- string - string Class.Property { get; set; } 
- void Class.Method();

Changed:

 - object Cell.OldPropertyName => object Cell.NewPropertyName

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 80**: **[Warning]** Failed to run script W:\rsmg-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C23%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807231718497004-402%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2wisiHrehBP2OZRUvgh89Xg%2FxbmchFeo0UtSEtLGFd0%3D&st=2018-07-23T17%3A15%3A23Z&se=2018-08-23T17%3A20%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 80**: **[Warning]** Failed to run script W:\zrq1-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C23%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807231801070558-402%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zVMgU4fKE9EgqBEBuWtLSfn07pCiRSFKtLl2n799ZXI%3D&st=2018-07-23T17%3A57%3A16Z&se=2018-08-23T18%3A02%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
Moving to: https://github.com/xamarin/Essentials/pull/403 as this is larger due to some weird merging.

**Comment by jamesmontemagno** [comment]
Thank you for bring this to our attention

**Pull request closed without merging**
