### PR TITLE
GH-676 Require To Check GPS Location is Fake Or Not In GeoLocation

### PR DESCRIPTION
**Pull request by pictos**
### Description of Change ###

Added a new propertie in Location class.

### Bugs Fixed ###

- Related to issue #676 

### API Changes ###

Added: 
 
- `boolLocation.IsFromMockProvider{ get; set; }`

Changed:

Added the property in `LocationExtensions.plataform.ToLocation()`
 
### Behavioral Changes ###

Now return a new field. After review I commit the update documentation

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Looks like a bunch of random changes got in there...

**Comment by pictos** [comment]
I've had some issues with msbuild and it seems like I've done it. If this is confusing, I can make the other PR cleaner.

**Comment by jamesmontemagno** [comment]
Just need to update docs and samples now :)

**Comment by pictos** [comment]
I revert the files and remove the ! in LocationExtentions.android.cs . I think now it's ok

**Comment by jamesmontemagno** [comment]
Looks good to me, just samples + docs need updating and good to go :)

**Comment by pictos** [comment]
@mattleibow , @jamesmontemagno  when I try to run the msbuild script I get this error: 
```
error MSB3030: could not copy file "C:\Git
Hub\XE\Essentials\Xamarin.Essentials\bin\Release\monoandroid81\MonoAndroid81\Xamarin.Essentials.dll" because he was not
 found. [C:\GitHub\XE\Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj]
```
But the dll is generate in  
`C:\GitHub\XE\Essentials\Xamarin.Essentials\bin\Release\monoandroid81\81\Xamarin.Essentials.dll`

I solved this problem renamed the folder 81 to MonoAndroid81

**Pull request merged**
