### PR TITLE
GH-368: Allow for unicode in host names and escape query

### PR DESCRIPTION
**Pull request by Redth**
### Description of Change ###

Previously we were passing the the url as is to each platform and letting it deal with how to parse into the platform specific url.

This handles unicode domain names (IDN Mapping aka PunyCode) for the domain, but also reconstructs the url based on the parsed System.Uri from the original string, and so the PathAndQuery will be the % escaped version which will account for unicode characters in it as well.

Finally, on iOS and Android we are using AbsoluteUri to end up with the fully IDN mapped and % encoded URL to pass to the system URL types.

Describe your changes here. 

### Bugs Fixed ###

- Related to issue #368

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

None

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807181832591768-393%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5bwDpPP6y2agqvlHb0yj2bzaPz5p0RVNnCqdfvnOnBo%3D&st=2018-07-18T18%3A28%3A55Z&se=2018-08-18T18%3A33%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
build

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Tests/Browser_Tests.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Tests/Browser_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807182034565818-393%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aqKsT%2FDxA5v8P74u%2F5wveWNuatAj6NdFnE44kOMH1lk%3D&st=2018-07-18T20%3A30%3A53Z&se=2018-08-18T20%3A35%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Tests/Browser_Tests.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Tests/Browser_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807182045036877-393%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=121yKmQUDroVXbHjflFCgy9XhNrxSGlQH5hO2rEgvFE%3D&st=2018-07-18T20%3A40%3A59Z&se=2018-08-18T20%3A45%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/build.cake](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/DeviceTests/build.cake) | :white_check_mark:Succeeded | |
[Tests/Browser_Tests.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Tests/Browser_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807191521079707-393%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=U%2FuNeSdPwFwPbUcT39%2Bpa45mEsGx%2Fg3DUZGYD6FHT28%3D&st=2018-07-19T15%3A17%3A09Z&se=2018-08-19T15%3A22%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/build.cake](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/DeviceTests/build.cake) | :white_check_mark:Succeeded | |
[Tests/Browser_Tests.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Tests/Browser_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.android.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.ios.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Browser/Browser.shared.cs](https://github.com/xamarin/Essentials/blob/browser-url-sanitize/Xamarin.Essentials/Browser/Browser.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201807191847343478-393%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XJ4O4Iqsv%2FiBHKtw9Edzct7P25IBaFWh2igxSsgDktY%3D&st=2018-07-19T18%3A43%3A31Z&se=2018-08-19T18%3A48%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
