### PR TITLE
OrientationSensor: use proper reference frame on iOS

### PR DESCRIPTION
**Pull request by janusw**
### Description of Change ###

* start MotionManager with reference frame XTrueNorthZVertical,
  in order to have a fixed frame that is not arbitrary
* rotate the obtained quaternions by 90 degrees, so that Y points north instead of X

### Bugs Fixed ###

- Related to issue #981

### API Changes ###

No API changes!

### Behavioral Changes ###

The OrientationSensor uses a fixed reference frame on iOS now, matching the documentation and the behavior on Android. Up to now, the frame was arbitrary and depended on the orientation of the device when the sensor was started.

No documentation update is necessary because the implementation was fixed to match the documentation :)

Tests were performed manually on an iPhone 8 with iOS 13.2. I wouldn't know how to write an automated test for this.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Also, if you can sign: https://github.com/xamarin/Essentials/pull/988#issuecomment-554272685

**Comment by janusw** [comment]
Thanks for the quick review and approval, @jamesmontemagno!

As mentioned before, I don't think any documentation changes are necessary. The documentation as such is pretty clear, it was just the implementation on a specific platform that did not match the documented behavior.


> Also, if you can sign: [#988 (comment)](https://github.com/xamarin/Essentials/pull/988#issuecomment-554272685)

Will do soon!

**Comment by janusw** [comment]
@jamesmontemagno I rebased the branch to current master, squashed both commits into one and signed the CLA. Hope this can be merged now ...

**Comment by janusw** [comment]
> @jamesmontemagno I rebased the branch to current master, squashed both commits into one and signed the CLA. Hope this can be merged now ...

Since I rebased the branch, it seems I need another review here (sorry about that). The content of the patch is unchanged, though ...

**Pull request merged**
