### PR TITLE
[secure-storage] iOS: broaden record query

### PR DESCRIPTION
**Pull request by Redth**
### Description of Change ###

On iOS in KeyChain, we were querying for existing records matching the expected `Account` and `Service` (good), but also the `Label` (questionably ok), and the `Accessible` (bad).

What happened was, in v0.6.0 we never set the `Accessible` property, and when an app was upgraded to v0.7.0.17 where we started setting that value, we also started looking up existing records having the new default `Accessible` value, however the record didn’t match, even though one existed with the given key, and a runtime error occurred.

Upon further investigation it looks like `Service` and `Account` are the true ‘unique’ identifying values for a given `SecRecord`, and so those are the only fields we should be using when querying for existing records.

This change removes the other fields from the existing record lookup query.

### Bugs Fixed ###

- #317 

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

None.

### Behavioral Changes ###

Fixes incorrect behaviour mentioned above.

### PR Checklist ###

- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/Redth/Caboodle/blob/secure-storage-ios-bugfix/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806251439060110-321%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ieYluB0RQ%2F408792YQKUl3oYwZON0BjxDM2VEHED8k8%3D&st=2018-06-25T14%3A35%3A01Z&se=2018-07-26T14%3A40%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/Redth/Caboodle/blob/secure-storage-ios-bugfix/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806251455199259-321%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5hSh%2Beh3XCIUg3m3H67uJbNEKSQT8wsFY4DtuM9cGB8%3D&st=2018-06-25T14%3A51%3A12Z&se=2018-07-26T14%3A56%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
build

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/Redth/Caboodle/blob/secure-storage-ios-bugfix/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806251559360334-321%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KP6gTJZIr%2FrWypYtqrxF6997XPBVKEPAx1g8x7%2B%2FI%2FM%3D&st=2018-06-25T15%3A55%3A27Z&se=2018-07-26T16%3A00%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/Redth/Caboodle/blob/secure-storage-ios-bugfix/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806251651105154-321%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=W4k9T02OvtbZhg9at1BoET7AwAQb46LFM3d%2BTheOgls%3D&st=2018-06-25T16%3A47%3A04Z&se=2018-07-26T16%3A52%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
build

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/Redth/Caboodle/blob/secure-storage-ios-bugfix/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201806251740448603-321%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pssmfrST2XgbqhS%2BcHDzBOPKl7C6WcbX2Ra14Rzi8TQ%3D&st=2018-06-25T17%3A36%3A43Z&se=2018-07-26T17%3A41%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Redth** [comment]
build

**Pull request merged**
