### PR TITLE
Fix to fatal iOS 13 memory leak when using TextToSpeach.SpeekAsync #1112

### PR DESCRIPTION
**Pull request by baskren**
### Description of Change ###

In **TextToSpeech.ios.tvos.watchos.cs**:

 - Went **_from_** one instance of **AVSpeechSynthesizer** being instantiated per `TextToSpeach.SpeakAsync` call **_to_** a single static lazy instance of **AVSpeechSynthesizer**.
 - Instantiated the (per `TextToSpeach.SpeakAsync` call) instance of **AVSpeechUtterance** in a `using` statement, to implicitly invoke a `dispose()` upon it.

#### TESTS #### 
To test, use the TextToSpeach sample in the existing Xamarin.Essentials.Sample.iOS app with **Xamarin.Profiler** or **Instruments**.  If there is a way to automate this, I'm all ears.

#### SAMPLES ####
The TextToSpeach sample in the existing Xamarin.Essentials.Sample.iOS app is capable of demonstrating this issue.  However, the [demo project](https://github.com/baskren/Speak_n_Leak) in issue #1112 is more concise.

#### UPDATED DOCUMENTATION ####
Nothing `public` was effected by this change.

### Bugs Fixed ###

 - issue https://github.com/xamarin/Essentials/issues/1112
 - issue https://github.com/xamarin/Essentials/issues/1110

### API Changes ###

none

### Behavioral Changes ###

none

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@praeclarum are you able to look at this PR? You have a lot of experience with AVSpeechSynth. 

I remember that in my plugin we moved to creating a new one because if routes changed then it would get messed up: https://github.com/jamesmontemagno/TextToSpeechPlugin/pull/59

**Comment by baskren** [comment]
@jamesmontemagno You are likely right ... this is just the kind of thing I suspected could be of concern.  My feelings won't be hurt if someone else has a way to fix issue #1112 and prevent https://github.com/jamesmontemagno/TextToSpeechPlugin/pull/59.  I am guessing @nexxuno was on the right track with https://github.com/jamesmontemagno/TextToSpeechPlugin/pull/59/commits/77ab3e913b843a2297b8fab124d316e8521c4f73.

**Comment by praeclarum** [comment]
I have always used a singleton synthesizer object. I wonder if that bug that got filed and your PR was just because of a transient iOS bug or maybe the audio session was misconfigured. This change seems right to me.

There are other changes outside the scope of the synthesizer, do you want me to review those?

**Comment by jamesmontemagno** [comment]
@praeclarum nope, just the synthesizer one. Would be good to just test the audio route change. perhaps it was an iOS thing back in the day and no longer an issue.

**Comment by baskren** [comment]
@jamesmontemagno & @praeclarum 

What would a change-of-audio-route test look like?  Start with using device speakers and then switch to Bluetooth speakers?

**Comment by praeclarum** [comment]
@baskren Yep that would be a change. Also settings changes can cause it, backgrounding, switching audio session configuration (global properties in AVFoundation), phase of moon...

Apple makes no mention of needing to handle it in their docs though.

**Comment by baskren** [comment]
@praeclarum 

I'll be able to test this on Monday.

**Comment by nexxuno** [comment]
@baskren: yes I had problem with backgrounding and route changes for example.

(ps. At a glance I'm seeing a possible bug in semaphore handling when looking at my commit cited above)

**Comment by baskren** [comment]
@jamesmontemagno, @praeclarum, @nexxuno 

I've successfully tested the commit on production devices running iOS 13.3.1 (iPad Air 2) and 12.4 (iPad 6th gen).

**Comment by jamesmontemagno** [comment]
@nexxuno can you describe and point out the code more?

**Comment by nexxuno** [comment]
> 
> 
> @nexxuno can you describe and point out the code more?

Hello, do you need a comment about my old commits or something else?

I remember that my first fix involved recreating the synth object each time the route changed (while disposing the old one) but then you suggested to create a new one each time SpeechUtterance was called and then disposing it at the end of it's usage. But I don't know if it's relevant anymore 2 years later...

Everything about that fix was about a functional bug (audio problems when switching to background processing) while this looks about memory issues.

**Comment by jamesmontemagno** [comment]
Thanks @nexxuno yeah, just wanted to make sure we checked to make sure we didn't regress at all from what yours fixed.

**Pull request merged**
