### PR TITLE
Geolocation - Location Updates #290 - added ContinuousLocationListene…

### PR DESCRIPTION
**Pull request by alexreich**
…r ported from Geolocator.Plugin.GeolocationContinuousListener

### Description of Change ###

Attempted port from Geolocator.Plugin.GeolocationContinuousListener 

### Bugs Fixed ###

- Related to issue #

Geolocation - Location Updates #290

### API Changes ###

Added: 
 
- ContinuousLocationListener

Changed:

### PR Checklist ###

- [ ] Has tests (omitted, do not have apis installed)
- [ ] Has samples (omitted, do not have apis installed)
- [ X] Rebased on top of master at time of PR
- [ X] Changes adhere to coding standard
- [ ] Updated documentation (ported as-is)

### CODE REVIEW

**Comment by JorgeKleber** [comment]
this function will be release?

**Comment by FIELDPOINT** [comment]
Any idea when this will be released? Desperately need this.

**Comment by JorgeKleber** [comment]
anybody there?

**Comment by alexreich** [comment]
@JorgeKleber All the checks have passed - needs someone w/authorization to merge this pr.

**Comment by Happypig375** [comment]
@jamesmontemagno

**Comment by Bejasc** [comment]
@Redth any chance of this getting approved soon?

**Comment by Redth** [comment]
We are looking at background type tasks in the future (like 1.6.0 and beyond).

**Comment by jamesmontemagno** [comment]
For this, there is really two things:

1.) Continuous updates while the app is open.
2.) Continuous updates while the app is in the background.

The first one isn't too tricky, but I don't know how useful it is (chime in #290)
The second we need to do a full spec for background tasks and crossplatform background updates. This would also have a new class most likely. 

This PR just brings in a new class and not actually any new functionality that could be used.  I would also say my geolocation plugin does work, but is not the best modern day example of doing it IMHO.

**Comment by FIELDPOINT** [comment]
@jamesmontemagno we have been using your plugin for this. I could not find a good sample for the Background updates for Xamarin Forms which would really be helpful for a lot of people.

**Comment by angelieri** [comment]
> For this, there is really two things:
> 
> 1.) Continuous updates while the app is open.

It is very useful to warming up GPS and catch more precise location.
Example:
The user opens the app.
GPS starting to receive some locations.
When the user really go to the step that needs a GPS coordinates, no need to wait.

**Comment by mattleibow** [comment]
Thanks for this PR, however I am going to be closing this as it is superseded by #1579 and a more complete implementation.

**Pull request closed without merging**
