### PR TITLE
GH-1180 ; Don't launch new task on custom tabs.

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Based off feedback of launching new task for system. Can't find google docs showing to do it how we have it and my old plugin didn't have it.

### Bugs Fixed ###

- Related to issue #1180

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### Behavioral Changes ###

Will now launch in same activity.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by Redth** [comment]
The original issue #225 was basically:

> Calling StartActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag.

Which makes me think we should maybe check if we have the Activity's context first, and if not, still add the NewTask flag because it's all we can do at that point.

**Comment by jamesmontemagno** [comment]
I think we want to add back in:

#if __ANDROID_24__	
                    if (Platform.HasApiLevelN)	
                        flags |= ActivityFlags.LaunchAdjacent;	
#endif

**Comment by rickclephas** [comment]
> I think we want to add back in:
> 
> #if __ANDROID_24__	
>                     if (Platform.HasApiLevelN)	
>                         flags |= ActivityFlags.LaunchAdjacent;	
> #endif 
> 
> 
> 

Good point but the `LaunchAdjacent` flag requires the `NewTask` flag. See [FLAG_ACTIVITY_LAUNCH_ADJACENT](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_LAUNCH_ADJACENT).

IMHO multi-window support should be an option in `BrowserLaunchOptions`.

**Comment by Redth** [comment]
So, I've added to this PR a new `BrowserLaunchFlags` and property on `BrowserLaunchOptions`.  My thinking here is we can use this to set some platform specific things like Launching adjacent on android or presenting as Modal on iOS.  Things that are useful to expose but don't really have a cross platform meaning.

This takes care of adding optionally adding LAUNCH_ADJACENT flag for Android where we otherwise wouldn't want NewTask.  Thoughts?

**Comment by rickclephas** [comment]
> So, I've added to this PR a new `BrowserLaunchFlags` and property on `BrowserLaunchOptions`.  My thinking here is we can use this to set some platform specific things like Launching adjacent on android or presenting as Modal on iOS.  Things that are useful to expose but don't really have a cross platform meaning.
> 
> This takes care of adding optionally adding LAUNCH_ADJACENT flag for Android where we otherwise wouldn't want NewTask.  Thoughts?

Sounds good to me! 🙂

**Comment by jamesmontemagno** [comment]
Just running final test and should be good

**Pull request merged**
