### PR TITLE
Allow JNI activation of EssentialsNetworkCallback to fix #1996

### LINKED ISSUE #1996: [Bug] Connectivity causes app crash on Android since EssentialsNetworkCallback is already disposed (Java.Interop.JavaLocationException)
### Description
Recently we experienced app crashes in our app on Android after we upgraded to XE 1.7.2. Probably due to #1568 . In our app we subscribe and unsubscribe to ``Connectivity.ConnectivityChanged`` event a few times during startup (not often). In some cases we observe app crashes where the app terminates with JavaLocationException shortly after starting (when the connectivity events are subscribed). 

We think the reason is that by unsubscribing the event Connectivity stops and removes the listeners and disposes ``EssentialsNetworkCallback``. However there is a (not so low) chance that callback invocation is already scheduled while managed wrapper ``EssentialsNetworkCallback`` is disposed (even if listener was currectly unregistered before). In this case the Java native/JNI domain cannot invoke the callback anymore causing the exception shown below which terminates the app.

Note that other XE modules like Magnetometer might also be affected by the same problem, see for example #1272 .

This is the exception we see (note that the stack trace might be slightly different depending on which network event is being delivered):
```
04-15 13:17:35.653 31179 31227 E AndroidRuntime: FATAL EXCEPTION: ConnectivityThread
04-15 13:17:35.653 31179 31227 E AndroidRuntime: Process: ***, PID: 31179
04-15 13:17:35.653 31179 31227 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NotSupportedException: Unable to activate instance of type Xamarin.Essentials.Connectivity+EssentialsNetworkCallback from native handle 0x780d4cef34 (key_handle 0x522746d). ---> System.MissingMethodException: No constructor found for Xamarin.Essentials.Connectivity+EssentialsNetworkCallback::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
04-15 13:17:35.653 31179 31227 E AndroidRuntime:    --- End of inner exception stack trace ---
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x000b5] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:    --- End of inner exception stack trace ---
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017e] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x00023] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at Android.Net.ConnectivityManager+NetworkCallback.n_OnCapabilitiesChanged_Landroid_net_Network_Landroid_net_NetworkCapabilities_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_network, System.IntPtr native_networkCapabilities) [0x00000] in <e41c0215a1b34d5f990de0d09dbe0e84>:0
04-15 13:17:35.653 31179 31227 E AndroidRuntime:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr,intptr,intptr)
04-15 13:17:35.653 31179 31227 E AndroidRuntime: 	at crc64a0e0a82d0db9a07d.Connectivity_EssentialsNetworkCallback.n_onCapabilitiesChanged(Native Method)
04-15 13:17:35.653 31179 31227 E AndroidRuntime: 	at crc64a0e0a82d0db9a07d.Connectivity_EssentialsNetworkCallback.onCapabilitiesChanged(Connectivity_EssentialsNetworkCallback.java:50)
04-15 13:17:35.653 31179 31227 E AndroidRuntime: 	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3580)
04-15 13:17:35.653 31179 31227 E AndroidRuntime: 	at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3793)
04-15 13:17:35.653 31179 31227 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-15 13:17:35.653 31179 31227 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
04-15 13:17:35.653 31179 31227 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

Here we see the course of events during a local repro:
```
Try no.: 0
// ConnectivityChanged subscribed
[App]  INFO 2022-04-20 10:54:48.8057 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
Thread started:  #12
// ConnectivityChanged unsubscribed and subscribed again immediately afterwards
[App]  INFO 2022-04-20 10:54:48.9300 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 1
// ConnectivityChanged subscribed again ...
[App]  INFO 2022-04-20 10:54:48.9387 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:48.9689 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 2
[ConnectivityManager.CallbackHandler] callback not found for CALLBACK_AVAILABLE message
[App]  INFO 2022-04-20 10:54:48.9744 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:49.0019 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 3
[ConnectivityManager.CallbackHandler] callback not found for CALLBACK_AVAILABLE message
[App]  INFO 2022-04-20 10:54:49.0071 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:49.0336 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 4
[App]  INFO 2022-04-20 10:54:49.0364 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager.CallbackHandler] callback not found for CALLBACK_AVAILABLE message
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:49.0649 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 5
[App]  INFO 2022-04-20 10:54:49.0698 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager.CallbackHandler] callback not found for CALLBACK_AVAILABLE message
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:49.1251 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 6
[App]  INFO 2022-04-20 10:54:49.1314 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:49.1907 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
[ConnectivityManager.CallbackHandler] callback not found for CALLBACK_AVAILABLE message
Try no.: 7
[App]  INFO 2022-04-20 10:54:49.1987 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:49.2554 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 8
[App]  INFO 2022-04-20 10:54:49.2633 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
**System.NotSupportedException:** 'Unable to activate instance of type Xamarin.Essentials.Connectivity+EssentialsNetworkCallback from native handle 0x71172f5744 (key_handle 0x69dc2ec).'

[ConnectivityManager] requestNetwork; CallingUid : 10262, CallingPid : 6993
[App]  INFO 2022-04-20 10:54:49.6225 [1/NetworkConnectivity] Un-subscribe ConnectivityChanged 
[ConnectivityManager] unregisterNetworkCallback; CallingUid : 10262, CallingPid : 6993
Try no.: 9
[App]  INFO 2022-04-20 10:54:49.6395 [1/NetworkConnectivity] Subscribe ConnectivityChanged 
```
### Steps to Reproduce

1. Ensure no other delegate is subscribed to ConnectivityChanged
2. Perform the following steps in a loop (usually appears after a few hundred iterations)
   a. Subscribe to ConnectivityChanged
   b. Unsubscribe to ConnectivityChanged

### Expected Behavior
ConnectivityChanged can be subscribed/unsubscribed multiple times without problems.

### Actual Behavior
App crashes when ConnectivityChanged is subscribed/unsubscribed multiple times.

### Basic Information

- Version with issue: 1.7.2
- Last known good version: 1.7.0
- Platform Target Frameworks: 
  - Android: >= 7.1

### Screenshots
None

### Reproduction Link
On request

### PR DESCRIPTION
**Pull request by cpraehaus**
### Description of Change ###
This avoids app crash with "NotSupportedException: Unable to activate instance of type Xamarin.Essentials.Connectivity+EssentialsNetworkCallback from native handle" in case callback invocation is scheduled but managed wrapper EssentialsNetworkCallback has already been disposed.

This change allows JNI to create managed wrapper in case original ```EssentialsNetworkCallback``` is already disposed. In such a case ```EssentialsNetworkCallback``` is created, the callback is delivered and ignored and then the callback object disposes itself to avoid mem-leak.

### Bugs Fixed ###

- Related to issue #1996 

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of `main` at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Review by msanna95 — APPROVED** [review]

**Comment by NZKobra** [comment]
Bump - Can we get this reviewed? 

This issue is causing crashes in production apps...

**Review by PTancek — APPROVED** [review]

**Comment by PTancek** [comment]
Could we please finish this issue? This is still causing crashes in our production

**Comment by epsmae** [comment]
Any news on that?

**Comment by vividos** [comment]
@jfversluis I'm also gettting some crashes in AppCenter for one of my apps. Is it already fixed in MAUI Essentials?

**Comment by PTancek** [comment]
To anyone wtill facing this issue. We went back to using https://www.nuget.org/packages/Xam.Plugin.Connectivity and the issue went away. 
Even though that packages is not maintained any more, it is still compatible with the latest Xamarin.Forms version (we are currently on 5.0.0.2545)

Really dissapointed on this issue with xamarin essentials

**Comment by jonpryor** [comment]
I don't like this change, adding `(IntPtr, JniHandlerOwnership)` constructors often hides problems.  The `NotSupportedException` + `MissingMethodException` is thrown because Java code is attempting to invoke a method on a C# class, and the association between the Java-side instance and the C#-side instance has been broken.

*Why* has it been broken?  Unless you don't care, and you'll *never* car, adding a `(IntPtr, JniHandleOwnership)` constructor "fix the bug" by hiding the issue.  It's not a fix itself.

Enter a quick investigation: https://github.com/xamarin/Essentials/issues/1996#issuecomment-1551828249

I *think* this is actually a multithreading issue between Java code invoking methods on `EssentialsNetworkCallback` and the unregistration code of `Connectivity.UnregisterNetworkCallback()`.  If this assumption is correct, the *actual* course of action is to *remove this `.Dispose()` call*:

https://github.com/xamarin/Essentials/blob/25ceeea887c50e5194d746bd159be1f143e26157/Xamarin.Essentials/Connectivity/Connectivity.android.cs#L91

The GC can cleanup the instance "later", once Java code is no longer referencing the `EssentialsNetworkCallback` instance.

**Comment by vividos** [comment]
@jonpryor I also got the sporadic errors in AppCenter for some time, and I had the impression that it's only happening when the C# part of the app is long gone, but the Java part tries to receive a broadcast and had to "re-create" the C# class, since it was already GCd. At some point in time I added removing the event handler again:
 https://github.com/vividos/WhereToFly/blob/c1fcc549047e3af21b9dd47a980a5cafa4dbbb02/src/App/Core/Views/MapPage.cs#L851

I got no recent errors in AppCenter anymore, although I can't say that this was the fix, as not many people use my app.

**Pull request closed without merging**
