### PR TITLE
Handle new iOS location permission event (issue 1390)

### LINKED ISSUE #1390: [Bug] in iOS 14 await Permissions.RequestAsync<Permissions.LocationXXX>() does not return after the pop-up is closed
### Current Behavior

in iOS 14 when permission is accepted and right after the pop-up is closed
await Permissions.RequestAsync<Permissions.LocationWhenInUse>(); or
await Permissions.RequestAsync<Permissions.LocationAlways>();
never returns, or throws an exception the first time called.

### Expected Behavior

in iOS 14 when permission is accepted and right after the pop-up is closed
await Permissions.RequestAsync<Permissions.LocationWhenInUse>(); or
await Permissions.RequestAsync<Permissions.LocationAlways>();
returns  PermissionStatus.Granted.

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: not known
- IDE: Visual Studio for Mac 8.7.8 (build 4)
- Platform Target Frameworks:
  - iOS:  Xamarin.iOS 14.0.0.0
- Affected Devices: Simulator iPhone 11, iOS 14.0

### PR DESCRIPTION
**Pull request by msjogren**
### Description of Change ###

Adapts code to new CLLocationManager APIs in iOS 14 (tvOS 14, watchOS 7) while keeping existing logic for older versions.

### Bugs Fixed ###

- Fixes #1390 

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of `main` at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by mattleibow** [comment]
@msjogren thanks for this PR. It pretty much does everything right.

I hope you don't mind that I pushed to your branch. I was trying a few things on what you did and I replaced the events with a delegate class. I as trying to find a way to not use the new members so we can support VS 2017 for a tiny bit longer. I'm going to probably push out a PR NuGet to the preview feed for anyone with VS2017 to test.

**Comment by msjogren** [comment]
@mattleibow Not at all, I like your version even better. I didn't realise it would cause issues with VS2017.

**Comment by MitchBomcanhao** [comment]
@msjogren does this change force us to be on xcode 12? we're still on xcode 11.5 due to some package namespace conflicts in AppCenter, and when updating to essentials 1.6.0 the build will fail 

`MTOUCH : error MT2101: Can't resolve the reference 'CoreLocation.CLAuthorizationStatus CoreLocation.CLLocationManager::get_AuthorizationStatus()', referenced from the method 'System.Void Xamarin.Essentials.Permissions/LocationWhenInUse/ManagerDelegate::DidChangeAuthorization(CoreLocation.CLLocationManager)' in 'Xamarin.iOS`

**Comment by msjogren** [comment]
@MitchBomcanhao It requires Xamarin.iOS 14. I don't have a machine around to try but according to [this](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/old-version-xcode) you may still be able to use an older version of Xcode.

**Pull request merged**
