### PR TITLE
GH-440 Fix iOS Navigation & UWP/Android Navigation too!

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Implement UWP navigation modes and also fix iOS navigation.

Added "none" mode.

### Bugs Fixed ###

- Related to issue #440

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- enum - enum MapDirectionsMode.None { get; set; } 

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Samples/Samples/View/MapsPage.xaml](https://github.com/xamarin/Essentials/blob/bug/issue-440/Samples/Samples/View/MapsPage.xaml) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/MapsViewModel.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Samples/Samples/ViewModel/MapsViewModel.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/MapDirectionsMode.shared.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/MapDirectionsMode.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/MapLaunchOptions.shared.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/MapLaunchOptions.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/Maps.ios.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/Maps.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/Maps.uwp.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/Maps.uwp.cs) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/MapDirectionsMode.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/Xamarin.Essentials/MapDirectionsMode.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/Maps.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/Xamarin.Essentials/Maps.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/MapsLaunchOptions.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/Xamarin.Essentials/MapsLaunchOptions.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C3%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201808031703484584-444%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9ligZR4IY83lVgWdxLJAMnoQJOHehLuQN58b3yeEBkQ%3D&st=2018-08-03T16%3A59%3A58Z&se=2018-09-03T17%3A04%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Redth** [comment]
Should we do something similar on Android to handle directions mode?

https://developers.google.com/maps/documentation/urls/android-intents#launch_turn_by_turn_navigation

It looks like we could technically call the intent uri `google.navigation:` and add a `mode=w` to it.  However this of course is more opinionated on which app it should use to launch navigation (though I wonder if other apps register themselves to handle that prefix and maybe this is ok).

**Comment by jamesmontemagno** [comment]
@Redth implemented!

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Samples/Samples/View/MapsPage.xaml](https://github.com/xamarin/Essentials/blob/bug/issue-440/Samples/Samples/View/MapsPage.xaml) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/MapsViewModel.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Samples/Samples/ViewModel/MapsViewModel.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/MapDirectionsMode.shared.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/MapDirectionsMode.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/MapLaunchOptions.shared.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/MapLaunchOptions.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/Maps.android.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/Maps.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/Maps.ios.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/Maps.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Maps/Maps.uwp.cs](https://github.com/xamarin/Essentials/blob/bug/issue-440/Xamarin.Essentials/Maps/Maps.uwp.cs) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/MapDirectionsMode.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/Xamarin.Essentials/MapDirectionsMode.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/Maps.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/Xamarin.Essentials/Maps.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/MapsLaunchOptions.xml](https://github.com/xamarin/Essentials/blob/bug/issue-440/docs/en/Xamarin.Essentials/MapsLaunchOptions.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C3%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201808032020279697-444%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xq2UPk4II8B7zA6BKMDWGdCU%2FgZYqUtB11SVvykd%2Bg4%3D&st=2018-08-03T20%3A16%3A34Z&se=2018-09-03T20%3A21%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
