### PR TITLE
Removed Method Group conversions, more additions to equality.

### PR DESCRIPTION
**Pull request by Mrnikbobjeff**
### Description of Change ###
Removed most method group conversions to be able to cache the delegate as this is currently forbidden by the standard for method group conversions. [Here](https://github.com/Mrnikbobjeff/BenchmarkingSolution/blob/master/BenchmarkingSolution/EnumAllocations.cs) is the enum case benchmark as linked in the first issue, [here](https://github.com/Mrnikbobjeff/BenchmarkingSolution/blob/master/BenchmarkingSolution/MethodGroupConversions.cs) we see the effect of method group conversions.

- Related to issue 
#1029, #965
### API Changes ###

None

### Behavioral Changes ###

They should simply see less allocations throughout the app. 

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
When it comes to this will have @terrajobst validate.

**Comment by terrajobst** [comment]
> When it comes to this will have @terrajobst validate.

@jaredpar is more appropriate to validate this change

**Comment by Mrnikbobjeff** [comment]
Just for further reference, the current c# spec says the following about method group conversions in section 6.6 :"A new instance of the delegate type D is allocated. If there is not enough memory available to allocate the new instance, a System.OutOfMemoryException is thrown and no further steps are executed."
Concerning anonymous, the C# spec states the following in section 6.5.1: "Conversions of semantically identical anonymous functions with the same (possibly empty) set of captured outer variable instances to the same delegate types are permitted (but not required) to return the same delegate instance."
There was some work going on to allow method group conversions to be cached, but this does not appear to be on the roadmap to happen in the near future.

**Comment by mattleibow** [comment]
Interesting... I always thought these anonymous delegates would be worse. Seems C# tries to catch me out even more ;)

**Comment by Mrnikbobjeff** [comment]
@jaredpar Did you have a change to look over the changes yet?

**Comment by jaredpar** [comment]
@Mrnikbobjeff the method group conversions to delegates look good

**Comment by AmrAlSayed0** [comment]
https://github.com/dotnet/roslyn/issues/5835 I think it is related to this issue, though this is the roslyn compiler, I don't know if the same issue is in the mono compiler.

**Comment by Mrnikbobjeff** [comment]
That was the issue I referenced in the ticket. No matter what mono does, as long as it abides by the standard it will be exactly the same. Feel free to try yourself with the linked benchmark, you just have to add a ClrJob for mono

**Pull request closed without merging**
