### PR TITLE
Xamarin.Android.Support.Core.Utils isn't needed for Monodroid90 and up

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

The only class that is part of *Xamarin.Android.Support.Core.Utils* in Monodroid90 is an obsolete BroadcastReceiver which Essentials doesn't use

The types used by early Monodroid versions looks to have been moved to the Compat library

This will simplify the transient dependencies for MonoAndroid 9.0 and up

### Behavioral Changes ###

This shouldn't change anything
### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Which broadcast receiver isn't being used?

**Comment by PureWeen** [comment]
WakefulBroadcastReceiver and WakefulBroadcastReceiverInvoker are the only classes that are in this dll Monodroid90 and up.

They were deprecated in *API level 26.1.0.*
https://developer.android.com/reference/android/support/v4/content/WakefulBroadcastReceiver

**Comment by rmarinho** [comment]
Can we merge this ?

**Comment by mattleibow** [comment]
Are we even using this package at all? Maybe we can just remove it?

**Comment by jamesmontemagno** [comment]
Test it out locally and good with it.

**Pull request merged**
