### PR TITLE
better UIColor conversion

### LINKED ISSUE #1572: [Bug] Unprecise UIColor conversion
### Description
The precision of the color conversion for UIColor (and perhaps also for NSColor & other platforms) can be improved.

### Steps to Reproduce

1. Show `UIColorPickerViewController` and enter `Display P3 Hex Color : #663399`
2. Get UIColor object from `UIColorPickerViewController` & call `ToSystemColor` on it
3. Print Color as Hex string

### Expected Behavior
#663399

### Actual Behavior
#653299

This is because the CGColor has these components:
Red: 101.999986320734
Green: 50.9999969601631
Blue: 153.000021278858

With the current conversion, the values are rounded down:
https://github.com/xamarin/Essentials/blob/0dba844e8085f7cb36d62115b005620d541e0fbd/Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.ios.tvos.watchos.cs#L15

I think this would be a better conversion method:
 
```
return Color.FromArgb((int)Math.Round(alpha * 255), (int)Math.Round(red * 255), (int)Math.Round(green * 255), (int)Math.Round(blue * 255)); 
```

### PR DESCRIPTION
**Pull request by tipa**
### Description of Change ###
Better UIColor conversion uses rounding instead of cutting off decimals

### Bugs Fixed ###
fixes #1572

### API Changes ###
none

### Behavioral Changes ###
none

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of `main` at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
Anything for the other platforms at all?

**Comment by tipa** [comment]
@jamesmontemagno Windows & Android are using bytes for their "platform colors" so the bytes from the "system color" can be used 1:1

**Comment by jamesmontemagno** [comment]
Should also add some tests -> https://github.com/xamarin/Essentials/blob/main/Tests/Color_Tests.cs

**Comment by tipa** [comment]
Just spent an hour trying to add tests but the solution wouldn't build on my VS4Mac and on Windows, VS kept freezing when trying to start a remote session or the iOS simulator wouldn't launch

**Comment by jamesmontemagno** [comment]
@mattleibow  good to go?

**Review by Redth — APPROVED** [review]

**Pull request merged**
