### PR TITLE
[Bug][Android] File Picker exception when using third-party file managers

### LINKED ISSUE #1444: [Bug][Android] File Picker exception when using  third-party file managers
### Description
An exception occurs when using third-party file managers.

Selecting files on WhatsApp app using this and other third-party file managers on phones that I tested works without errors.

[Exception StackTrace](https://gist.github.com/dimonovdd/48024ac15ee410e16650b5d5933e5627)

### Steps to Reproduce

1. Install [File Manager+](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager)
2.  Select File Manager+

### Basic Information

- Affected Devices: tested on several Androids 10

### Screenshots
image

### PR DESCRIPTION
**Pull request by dimonovdd**
### Description of Change ###

~~To resolve the exception, you should add this permission:~~
~~`<uses-permission android:name="android.permission.MANAGE_DOCUMENTS" /> `~~

PR corrected as described on https://github.com/xamarin/Essentials/issues/1444#issuecomment-710990613

### Bugs Fixed ### 
Fixes #1444

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of `main` at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Looks good, appreciate your contribution to the docs as well :)

**Review by jamesmontemagno — DISMISSED** [review]

**Comment by dimonovdd** [comment]
@jamesmontemagno
have you read this discussion?
#1444

**Comment by mattleibow** [comment]
I think we need to have a look at the comments on the issue before we merge.

**Comment by mattleibow** [comment]
@dimonovdd should we also be removing the `intent.AddFlags(ActivityFlags.GrantPersistableUriPermission); ` flag?

Looking at the docs, it appears that it just opens up the possibility, but doesn't to anything else.

**Comment by dimonovdd** [comment]
> removing the `intent.AddFlags(ActivityFlags.GrantPersistableUriPermission)`

Yes, of course. I didn't notice

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
