### PR TITLE
Fixes #258 and Fixes #255

### LINKED ISSUE #255: Failing to install on the Android Project
### Description
Installing the package into xamarin.forms project fails for the android project. Installs fine for the shared and iOS projects. 
Errer message -

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Numerics' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
This collection is read-only.			0	

### Steps to Reproduce

1. Install nuget on all projects
2. Successed on shared and iOS
3. Fails for android

### Basic Information

- Version with issue: 0.6.0-preview
- IDE: VS 2017

### LINKED ISSUE #258: Incorrect Release notes link in NuGet
The Release Notes link is wrong in NuGet:
https://www.nuget.org/packages/Xamarin.Essentials

It's: 
https://github.com/xamarin/Xamarin.Essentials
the results in a 404.

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Fixing the NuGet link to the repo, and adding the "System.Numerics.Vectors" NuGet as a dependency for all platforms.

### Bugs Fixed ###

- Related to issue #258 and #255 

### API Changes ###

None.

### Behavioral Changes ###

The "System.Numerics.Vectors" NuGet is now always installed.

### PR Checklist ###

- [X] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard
- [X] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by mattleibow** [comment]
build

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/jamesmontemagno-patch-1/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C22%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805222103198314-259%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ySsU5%2Brn6HV7oylCFLu6ajx5Z2FF41zXuwXm1DQNjcI%3D&st=2018-05-22T20%3A59%3A51Z&se=2018-06-22T21%3A04%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/jamesmontemagno-patch-1/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/jamesmontemagno-patch-1/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805251606366142-259%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1oeXtvlauuJ4xpgN%2FmdKdZLoOgfXEDiHhi0xwAkOmJo%3D&st=2018-05-25T16%3A02%3A42Z&se=2018-06-25T16%3A07%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj](https://github.com/xamarin/Essentials/blob/jamesmontemagno-patch-1/DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj) | :white_check_mark:Succeeded | |
[DeviceTests/build.cake](https://github.com/xamarin/Essentials/blob/jamesmontemagno-patch-1/DeviceTests/build.cake) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/xamarin/Essentials/blob/jamesmontemagno-patch-1/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C25%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805251643422654-259%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=23B0jC6NLgCdCpNDpiN%2BcD0h8hIKWLCModszfaj4bhU%3D&st=2018-05-25T16%3A40%3A19Z&se=2018-06-25T16%3A45%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
