### PR TITLE
GH-457 Add new exception for SecureStorage

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Adds a new SecureStorageException to be thrown by iOS to provide more details.

### Bugs Fixed ###

- Related to issue #457 

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- SecureStorage 
- enum SecureStorageErrorCode

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [ x Has samples (if omitted, state reason in description)
- [x]Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Thoughts @Redth ?

**Comment by Redth** [comment]
I really think if we're going to do this, we should see how it maps to the other platforms.  I'm also wondering if having all of these error codes translated to an Essentials enum really adds that much more value than just writing out the SecStatusCode's .ToString() on iOS in the exception message?

I think the next step is to see what errors come out of android and UWP and how they would map to these enums, otherwise I don't think it makes a lot of sense to have an enum that's 'cross platform' but really only used in the case of iOS.

**Comment by mattleibow** [comment]
It might just be fine to use `Exception` and pass the native exception as the inner exception - that is what it is there for. ([inner exception docs](https://docs.microsoft.com/en-us/dotnet/api/system.exception.innerexception))

We can also create a new "generic" exception to throw so that we don't ever throw the base `Exception`.

Thoughts?

**Comment by mattleibow** [comment]
OK, so that was a partially useless comment - this is just an error code.
But, the same thing applies, we can either create a special `SecureStorageException`, or we can create a generic `XamarinEssentialsException` that is used for all the non-specific errors.

In either case, we can probably just create the exception with the message: `$"Error doing something: {errorCode.GetStatusDescription()} Error Code: {errorCode}."` (there appears to be an extension method `GetStatusDescription`)

**Pull request closed without merging**
