### PR TITLE
Add more extensions for location

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Describe your changes here. 

### Bugs Fixed ###

- Related to issue #

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- string - string Class.Property { get; set; } 
- void Class.Method();

Changed:

 - object Cell.OldPropertyName => object Cell.NewPropertyName

### Behavioral Changes ###

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/Types/Location.shared.cs](https://github.com/xamarin/Essentials/blob/feature/extension-enhancements/Xamarin.Essentials/Types/Location.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Types/LocationExtensions.shared.cs](https://github.com/xamarin/Essentials/blob/feature/extension-enhancements/Xamarin.Essentials/Types/LocationExtensions.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C11%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201808111909416246-469%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fpNvDCFYoHMtzeZmLkNSd40SyWBs2GxFrqwUrZ%2BbFhk%3D&st=2018-08-11T19%3A05%3A44Z&se=2018-09-11T19%3A10%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Xamarin.Essentials/Types/Location.shared.cs](https://github.com/xamarin/Essentials/blob/feature/extension-enhancements/Xamarin.Essentials/Types/Location.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Types/LocationExtensions.shared.cs](https://github.com/xamarin/Essentials/blob/feature/extension-enhancements/Xamarin.Essentials/Types/LocationExtensions.shared.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C11%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201808111909496895-469%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LQ3ca8cUx4NO5hiI3J1pjEHadC0yCNJ%2FGutaXybqKyQ%3D&st=2018-08-11T19%3A06%3A45Z&se=2018-09-11T19%3A11%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Mrnikbobjeff** [comment]
I started working on a variety of proposals open here, an I would love to see a strong type for distance, preferably with properties for km and miles. If we introduce the concept of a distance I would love to see it getting its own type. Would also be useful for geofencing

**Comment by jamesmontemagno** [comment]
We do have a distance type in there already of Miles or Kilometers. It is a simple enum ;)

**Pull request merged**
