### PR TITLE
GH-197: Moving screen metrics to a new API class

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

Moving screen metrics to a new API class #197

### Bugs Fixed ###

- Related to issue #197

### API Changes ###

Moved `ScreenMetrics` and `ScreenMetricsChanaged` from the `DeviceInfo` type into the `DeviceDisplay` type.

### Behavioral Changes ###

The only change was the move of the property and event.

### PR Checklist ###

- [X] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard
- [X] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/DeviceInfoViewModel.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Samples/Samples/ViewModel/DeviceInfoViewModel.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.ios.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.netstandard.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.shared.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.uwp.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.uwp.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.netstandard.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.shared.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/DeviceDisplay.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/Xamarin.Essentials/DeviceDisplay.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/DeviceInfo.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/Xamarin.Essentials/DeviceInfo.xml) | :white_check_mark:Succeeded | |
[docs/en/index.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/index.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C24%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201804241653370470-199%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=78EvsPquwsmRNrgyoMKpmpgNOgz2b15ywqvuJUIYoqI%3D&st=2018-04-24T16%3A49%3A47Z&se=2018-05-25T16%3A54%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/DeviceInfoViewModel.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Samples/Samples/ViewModel/DeviceInfoViewModel.cs) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/HomeViewModel.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Samples/Samples/ViewModel/HomeViewModel.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.ios.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.netstandard.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.shared.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.uwp.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.uwp.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.netstandard.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.shared.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/DeviceDisplay.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/Xamarin.Essentials/DeviceDisplay.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/DeviceInfo.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/Xamarin.Essentials/DeviceInfo.xml) | :white_check_mark:Succeeded | |
[docs/en/index.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/index.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C24%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201804241655169388-199%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IKTYRc9MYo8gDB9f87KM3eWrVe1PYE5tazejgXqG4%2Fg%3D&st=2018-04-24T16%3A51%3A21Z&se=2018-05-25T16%3A56%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
I will go update the actual docs for this and copy/paste some stuff around.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/DeviceInfoViewModel.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Samples/Samples/ViewModel/DeviceInfoViewModel.cs) | :white_check_mark:Succeeded | |
[Samples/Samples/ViewModel/HomeViewModel.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Samples/Samples/ViewModel/HomeViewModel.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.ios.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.netstandard.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.shared.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceDisplay/DeviceDisplay.uwp.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.uwp.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.netstandard.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.netstandard.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.shared.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.shared.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/Xamarin.Essentials.csproj](https://github.com/mattleibow/Caboodle/blob/move-device-display/Xamarin.Essentials/Xamarin.Essentials.csproj) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-android.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-android.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-ios.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-ios.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials-uwp.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials-uwp.xml) | :white_check_mark:Succeeded | |
[docs/en/FrameworksIndex/xamarin-essentials.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/FrameworksIndex/xamarin-essentials.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/DeviceDisplay.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/Xamarin.Essentials/DeviceDisplay.xml) | :white_check_mark:Succeeded | |
[docs/en/Xamarin.Essentials/DeviceInfo.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/Xamarin.Essentials/DeviceInfo.xml) | :white_check_mark:Succeeded | |
[docs/en/index.xml](https://github.com/mattleibow/Caboodle/blob/move-device-display/docs/en/index.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C24%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201804241815129655-199%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OcJH4gwED%2FFl0bc2IZm1UtnjuJi%2B9bDyUikLknF1ARA%3D&st=2018-04-24T18%3A11%3A21Z&se=2018-05-25T18%3A16%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
