### PR TITLE
GH-221: Add iOS SecAccessible properties

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Default iOS to AfterFirstUnlockThisDeviceOnly for the cross-platform API, but allow custom platform specific methods to pass in the SecAccessible

### Bugs Fixed ###

- Related to issue #221

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
-  Task<string> GetAsync(string key, SecAccessible accessible)
- Task SetAsync(string key, string value, SecAccessible accessible)

### Behavioral Changes ###

Nothing for iOS as this was the default before and what should be exposed.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C3%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805032146321529-223%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=auoe2Vrle4ddb4lPN6eCDWtcd8DRrU%2BRpkCDwKtMlfQ%3D&st=2018-05-03T21%3A42%3A34Z&se=2018-06-03T21%3A47%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jamesmontemagno** [comment]
@migueldeicaza to address the SecAccessible there is no real equivalent on Android/UWP to add to the cross platform API. This PR addresses setting it to the recommended default of AfterFirstUnlockThisDeviceOnly which matches other operating systems. At the same time offers up a platform specific overload to pass in the SecAccessible option to use.

**Comment by Redth** [comment]
I'm thinking we may want to provide an api to set the default on iOS.  I think users will generally want to set this once per application and forget about it and continue using `GetAsync` and `SetAsync` via their shared code.

Maybe we should do something like:

```
public partial class SecureStorage
{
    public static Security.SecAccessible DefaultAccessibility { get; set; } = 
        SecAccessible.AfterFirstUnlockThisDeviceOnly;
}
```

What do you think?

**Comment by jamesmontemagno** [comment]
I guess my current implementation it is on a key by key value compared to a global... I am not sure what iOS app devs would want really...

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C4%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805041553101201-223%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FZWcTC6IyTAlbKLbnhV8jPq9DzxvMBb%2FjmSSDaI%2FOZI%3D&st=2018-05-04T15%3A49%3A05Z&se=2018-06-04T15%3A54%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C4%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805041649120633-223%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eq0EVcJ809vXweUeZsVxg1naZXsUqWOxMW08X%2FdEdi0%3D&st=2018-05-04T16%3A45%3A06Z&se=2018-06-04T16%3A50%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by migueldeicaza** [comment]
This is a good step, but I wonder if we should support even as no-ops the other capabilities.

The other bit to think about is whether we should by default allow the key to be backed up when the user has encrypted backups.   That sounds like a good default.

**Comment by dend** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs) | :white_check_mark:Succeeded | |
[Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs](https://github.com/xamarin/Essentials/blob/feature/ios-secaccessible/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C4%5Cf63aadd0-c8f5-13ca-04e7-037e45f8c0b9%5CPullRequest%5C201805041837191765-223%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wDmpU5D79%2B0C2QLGEWLcYYXaXtAJTFDqOZYImIF6IJ0%3D&st=2018-05-04T18%3A33%3A23Z&se=2018-06-04T18%3A38%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
