### PR TITLE
Calendars Read-Only API 

### PR DESCRIPTION
**Pull request by builttoroamteam**
# Calendars Read-Only API

Calendars API for reading calendar/event information seamlessly across uwp, iOS and Android
(Issue https://github.com/xamarin/Essentials/issues/996)
# API

### Methods

| API | Description |
| ------------- | ------------- |
| ``Task<IEnumerable<Calendar>> GetCalendarsAsync()`` | Retrieve all calendars for device |
|  ``Task<IEnumerable<CalendarEvent>> GetEventsAsync( string calendarId = null, DateTimeOffset? startDate = null, DateTimeOffset? endDate = null)`` | Retrieve all events for a specified range/calendar. Null values for parameters will result in default values being used: null calendarId will return events from all calendares, startDate will default to the Now, endDate will default to startDate+14 days |
| ``Task<CalendarEvent> GetEventByIdAsync(string eventId)`` | Gets more detailed information about a specific event by the event id |

### Classes
```
public class Calendar
{
    string Id { get; set; }

    string Name { get; set; }
}

public class CalendarEvent
{
    string Id { get; set; }

    string CalendarId { get; set; }

    string Title { get; set; }

    string Description { get; set; }

    string Location { get; set; }

    bool AllDay { get; set; }

    DateTimeOffset Start { get; set; }

    DateTimeOffset? End { get; set; }

    TimeSpan? Duration { get; set; }

    IEnumerable<DeviceEventAttendee> Attendees { get; set; }
}

public class CalendarEventAttendee
{
    string Name { get; set; }

    string Email { get; set; }
}
```
# Scenarios

- User wants to see upcoming events.
- User wants to see who is attending an upcoming event.
- User wants to know when they will be free.

# Platform Compatibility
- Target Frameworks: 
  - iOS:  Support on iOS for the API
  - Android: Support on Android for the API
  - UWP: Support on UWP for the API
# Backward Compatibility
- UWP: Windows 10 (introduced v10.0.10240.0) 
(https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appointments.appointment)
- Android: android:minSdkVersion="14" 
(https://developer.android.com/reference/android/provider/CalendarContract)
- iOS: All versions until reminders are added, then iOS 6
(https://developer.apple.com/documentation/eventkit/ekeventstore)

# Contributors
@ScottBTR
@mkieres
@nickrandolph

### CODE REVIEW

**Comment by nickrandolph** [comment]
@mattleibow / @jamesmontemagno any suggestions on how to fix the failing build - afaik the test cases should be passing but fails during the build. Any assistance and/or feedback would be greatly appreciated.

**Comment by jamesmontemagno** [comment]
I am happy with this overall. I think we should pull in @redth's permissions and merge with some changes that were needed here for calendar and then would be good to go.

**Comment by jamesmontemagno** [comment]
My main thoughts are on naming...

* DeviceEvent -> I would choose DeviceCalendarEvent or just CalendarEvent
*DeviceEventAttendee -> Same... DeviceCalendarEventAttendee or just CalendarEventAttendee

I understand not using just "Calendar" as that is the class name to access things, however you could make it "Calendars" for the class? lol and have "Calendar" :)

**Comment by jamesmontemagno** [comment]
I wouldn't worry about the android test failing it is something with the build server.

**Comment by nickrandolph** [comment]
@jamesmontemagno we've updated the class names based on your suggestions. 
You mentioned pulling in some permissions - do we just need to rebase again off master, or are we waiting on another PR to be completed first?

**Comment by jamesmontemagno** [comment]
@nickrandolph the new permissions are in there. If you want to integrate with the new permissions that would be great!

**Comment by nickrandolph** [comment]
@jamesmontemagno / @Redth I've rebased onto the dev/calendar branch and have fixed up the usage for permissions. Let me know what else we need to adjust/work on.
Support for writing calendar events and dealing with recurring events is being worked on and will be submitted early in the new year, so it'd be good to get this PR merged so we only have a single PR related to calendars at a time.

**Comment by jamesmontemagno** [comment]
Awesome, that sounds great! Thanks for doing that. It is on the teams list to review and get in :) I am thinking we are doing 1.4.0 pretty soon so may get this in under a feature flag or put in right after to get into an early beta.

**Comment by nickrandolph** [comment]
I'd suggest going with the later option of early beta. Not sure how feature flagging would work since the calendar is pretty self contained, so feature flag wouldn't have much effect and just adds work to add/remove the flag.
If we can get it into beta, then we can integrate any feedback as part of adding support for recurring events (which will probably come before write support)

**Comment by nickrandolph** [comment]
@jamesmontemagno do you need anything more from us on this PR?

**Comment by ScottBTR** [comment]
Hi @jamesmontemagno, 

I've brought some naming convention changes across as listed below:
API - Calendar --> Calendars
Properties - Calendars --> CalendarList
Models:

DeviceCalendar --> Calendar
DeviceEvent --> CalendarEvent
DeviceEventAttendee --> CalendarEventAttendee

Which shouldn't cause any issues.

But I noticed that since the permissions update that uwp was no longer working for the calendars API, this was due to UWP appointments. Not using x:Capability/x:DeviceCapability but instead uap:Capability.

(See: Appointments
https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations?redirectedfrom=MSDN)

Because of this please note the changes I've made to Permissions.uwp.cs, let me know if this poses and problems or requires any changes.

Thanks!

**Comment by nickrandolph** [comment]
@jamesmontemagno @Redth this PR is currently targetting the dev/calendar branch which is from back in December. Any chance you can either update that branch or switch this PR to target a more recent branch. We're keen to rebase and test our read-only work before we start pushing the write functionality
We have the write functionality around 90% ready, just want to work out what the road to a merge is!

**Comment by nickrandolph** [comment]
@Redth is the plan still to get this merged for the 1.5 release? If so, can you instruct what you need us to do.

**Comment by Redth** [comment]
@nickrandolph no it will likely go into a 1.6.0. We had to rush 1.5 preview out to align with Forms’ AndroidX strategy.

**Comment by nickrandolph** [comment]
@Redth no probs. We're pretty close to pushing the write functionality. Would you be able to update the target branch for this PR so that we can rebase it? I would actually suggest keeping the target branch as master until you're close to being able to merge it. That way we can rebase and update it as necessary.

**Comment by Redth** [comment]
@nickrandolph sure, just updated it to target develop (which is as good as master right now).

**Comment by mattleibow** [comment]
Merging this into a local branch for better CI and so we can start the merge on this in #1384 . Looking pretty good so far.

**Pull request merged**
