### PR TITLE
Update Map.xml

### PR DESCRIPTION
**Pull request by mallibone**
Minor typo

### Description of Change ###

Fixes a minor typo.

### Bugs Fixed ###

None

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
so, we need to put into master first and then pull up to live.

**Comment by jamesmontemagno** [comment]
@mallibone can you re-do this pr and do it against master please?

**Comment by mallibone** [comment]
@jamesmontemagno I rebased from Xamarin/Essentials master branch and pushed again. Regarding targeting the master branch - the PR is targeting master no?

**Comment by jamesmontemagno** [comment]
got it! Looks good!!!!!!!!! thanks for the pr :)

**Pull request merged**
